#!/usr/xpg4/bin/sh -e

# Options

PREFIX=${BUILDPREFIX}

OS=${BUILD_ROOT}/cfbuild-openssl${PREFIX}
OSD=${BUILD_ROOT}/cfbuild-openssl-devel${PREFIX}

# To pick up libgcc_s.so.1, which is apparently not in dyld path.
export LD_LIBRARY_PATH=$PREFIX/lib

# Patch
$PATCH -p1 < 0009-Define-_XOPEN_SOURCE-as-600-on-Solaris-SPARC.patch

# Add dummy header files for features which are not compiled, but required
mkdir -p ${BUILD_ROOT}/../include/openssl
for f in idea srp; do
	touch ${BUILD_ROOT}/../include/openssl/${f}.h
done

# mkdir
test -d $PREFIX || ( sudo mkdir $PREFIX && sudo chmod 777 $PREFIX )
mkdir -p $PREFIX/include

# config misdetects architecture when building on a 64-kernel with 32-bit
# userspace.
if [ "$(uname -p)" = "i386" ]
then
    CONFIG="$PERL ./Configure solaris-x86-gcc"
else
    CONFIG="$PERL ./Configure solaris64-sparcv9-gcc"
fi

$CONFIG $(<config_flags_$ROLE.txt) \
    --prefix=$PREFIX  $LDFLAGS -lrt --libdir=lib

# Build

$MAKE depend
$MAKE

# Test

if [ "$TESTS" != no ]; then
    $MAKE test
fi

# Install

$MAKE DESTDIR=${BUILD_ROOT}/cfbuild-openssl-devel install_sw
$MAKE DESTDIR=${BUILD_ROOT}/cfbuild-openssl-devel install_ssldirs

# Package

rm -rf ${OSD}/bin
rm -rf ${OSD}/ssl
rm -rf ${OSD}/lib/fips*
rm -rf ${OSD}/lib/*.a
rm -rf ${OSD}/lib/cmake/OpenSSL

mkdir -p ${OS}/lib
mv ${OSD}/lib/libcrypto.so* ${OS}/lib
mv ${OSD}/lib/libssl.so* ${OS}/lib
mv ${OSD}/lib/ossl-modules ${OS}/lib/

