#!/usr/xpg4/bin/sh -e

# Options

PREFIX=/var/cfengine

OS=${BUILD_ROOT}/cfbuild-openssl${PREFIX}
OSD=${BUILD_ROOT}/cfbuild-openssl-devel${PREFIX}

# To pick up libgcc_s.so.1, which is apparently not in dyld path.
#TODO remove /usr/local/lib, I only put it here because the ~/perl-my binary needs it
export LD_LIBRARY_PATH=$PREFIX/lib:/usr/local/lib

# Patch

# Add dummy header files for features which are not compiled, but required
mkdir -p ${BUILD_ROOT}/../include/openssl
for f in idea srp; do
	touch ${BUILD_ROOT}/../include/openssl/${f}.h
done

# mkdir
test -d /var/cfengine || ( sudo mkdir /var/cfengine && sudo chmod 777 /var/cfengine )
mkdir -p /var/cfengine/include

# Perl
export PERL=$HOME/perl-my/bin/perl

# config misdetects architecture when building on a 64-kernel with 32-bit
# userspace.
if [ "$(uname -p)" = "i386" ]
then
    CONFIG="$PERL ./Configure solaris-x86-gcc"
else
    CONFIG="./config"
fi

echo $CONFIG shared  no-idea no-rc5 no-ssl3 no-dtls no-psk no-srp no-asm \
    --prefix=$PREFIX  $LDFLAGS
$CONFIG shared  no-idea no-rc5 no-ssl3 no-dtls no-psk no-srp no-asm \
    --prefix=$PREFIX  $LDFLAGS

# Build

$MAKE depend
$MAKE

# Test

if [ "$TESTS" != no ]; then
    $MAKE test
fi

# Install

$MAKE DESTDIR=${BUILD_ROOT}/cfbuild-openssl-devel install_sw

# Package

rm -rf ${OSD}/bin
rm -rf ${OSD}/ssl
rm -rf ${OSD}/lib/engines
rm -rf ${OSD}/lib/fips*
rm -rf ${OSD}/lib/*.a

mkdir -p ${OS}/lib
mv ${OSD}/lib/libcrypto.so* ${OS}/lib
mv ${OSD}/lib/libssl.so* ${OS}/lib

