#!/bin/sh -e

# Options

PREFIX=${BUILDPREFIX}

TT=${BUILD_ROOT}/cfbuild-lmdb${PREFIX}
TTD=${BUILD_ROOT}/cfbuild-lmdb-devel${PREFIX}

for i in 00*.patch; do
    $PATCH -p1 < $i
done
cd libraries/liblmdb
# Executable files taken from mdb-autoconf-generated.patch, which is generated
# from Git, and contains permission info, but patch -p1 cannot apply it.
# Use the following command to list the files.
#   grep -B1 '^new file mode.*755' mdb-autoconf-generated.patch
chmod 755 config.guess
chmod 755 config.sub
chmod 755 configure
chmod 755 depcomp
chmod 755 install-sh
chmod 755 missing

# Workaround for automake being sensitive to the order in which the generated
# files are applied. If Makefile.in is patched before aclocal.m4 (which it is,
# following natural file order), then it will try to rebuild Makefile.in, which
# it can't without automake. Work around it by touching that file.
touch Makefile.in

# Configure

# Build

./configure --prefix=$PREFIX
gmake

# Test

# Install

mkdir -p $TTD/bin
mkdir -p $TTD/lib
mkdir -p $TTD/include
mkdir -p $TTD/man/man1
gmake install prefix=${TTD}

# Package

rm -rf ${TTD}/man

mkdir -p ${TT}/bin ${TT}/lib
mv ${TTD}/bin/* ${TT}/bin
mv ${TTD}/lib/liblmdb.so* ${TT}/lib
