#!/bin/sh

# Installs given packages

if [ $# -eq 0 ]; then
  echo "Usage: $0 <pkg> [<pkg> ...]"
  exit 1
fi

for pkg in "$@"; do
  P_FILENAME=`basename $pkg`
  P_NAME=${P_FILENAME%.depot}

  if swlist ${P_NAME}; then
    sudo swremove ${P_NAME}
  fi

  sudo swinstall -s $pkg \*
done
