#!/bin/sh -ex

case "$0" in
  /*) SCRIPTDIR=`dirname "$0"`;;
  *) SCRIPTDIR=`pwd`/`dirname "$0"`;;
esac
BASEDIR=`dirname "$SCRIPTDIR"`
BASEDIR=`dirname "$BASEDIR"`

PATH="$PATH:$SCRIPTDIR"

usage()
{
  exec >&2
  echo "$0 <pkgname> <tests> <cross-target/native> <optimize> <debugsymbols> <version>"
  exit 1
}

fatal()
{
  echo "$@" >&2
  exit 42
}

if [ $# -ne 6 ]; then
  usage
fi

PKGNAME="$1"
TESTS="$2"
TARGET="$3"
OPTIMIZE="$4"
DEBUGSYM="$5"
VERSION="$6"

P=$BASEDIR/buildscripts/deps-packaging/$PKGNAME
PKGDIR=$BASEDIR/$PKGNAME/pkg

# Copy source code

rm -rf $BASEDIR/$PKGNAME
mkdir -p $PKGDIR

SRCFILES=$(pkg-get-src $P)

echo "$SRCFILES" | while read srcfile opts; do

  case "$srcfile" in
    *.gz|*.tgz)
      UNCOMPRESS=zcat;;
    *.bz2)
      UNCOMPRESS=bzcat;;
    *.xz)
      UNCOMPRESS=xzcat;;
    *)
      echo "Unknown compression: $srcfile"
      exit 42;;
  esac

  if [ x$opts = xsubdir ]; then
    $UNCOMPRESS $srcfile | tar -C $PKGDIR -xf -
  else
    TD=/tmp/`basename $srcfile`.$$
    mkdir -p "$TD"
    $UNCOMPRESS $srcfile | tar -C $TD -xf -
    mv $TD/*/* $PKGDIR
    rm -r "$TD"
  fi
done
cp -a $P/* $PKGDIR

# Prepare options

case "$TARGET" in
  native)
    ;;
  *)
    if [ -d $PKGDIR/mingw ]; then
      rm -rf $PKGDIR/debian
      mv $PKGDIR/mingw/debian $PKGDIR
    fi

    case "$TARGET" in
      x86)
        ARCH_OPTIONS="-ti686-w64-mingw32";;
      x64)
        ARCH_OPTIONS="-tx86_64-w64-mingw32";;
      *)
        fatal "Unknown architecture: $ARCH" 2>&1;;
    esac

    # Architecture needs to be the build machine architecture, since we will
    # install the package on that machine afterwards and the package
    # architecture needs to match.
    case "$(uname -m)" in
      i*86)
        ARCH_OPTIONS="$ARCH_OPTIONS -ai386";;
      x86_64)
        ARCH_OPTIONS="$ARCH_OPTIONS -aamd64";;
      *)
        fatal "Unknown architecture" 2>&1;;
    esac
    ;;
esac

case "$TESTS" in
  no)
    DEB_BUILD_OPTIONS="$DEB_BUILD_OPTIONS nocheck";;
  yes)
    ;;
  *)
    fatal "Unknown tests option: $TESTS";;
esac

case "$OPTIMIZE" in
  no)
    DEB_BUILD_OPTIONS="$DEB_BUILD_OPTIONS noopt";;
  yes)
    ;;
  *)
    fatal "Unknown optimize option: $OPTIMIZE";;
esac

case "$DEBUGSYM" in
  yes)
    DEB_BUILD_OPTIONS="$DEB_BUILD_OPTIONS nostrip";;
  no)
    ;;
  *)
    fatal "Unknown debugsym option: $DEBUGSYM";;
esac

BUILDDATE=$(date -R)

cat << EOF > $PKGDIR/debian/changelog
cfbuild-$PKGNAME ($VERSION) unstable; urgency=low

  * New build.

 -- CFEngine Autobuild System <buildscripts@cfengine.com>  $BUILDDATE
EOF

# Build!

cd $PKGDIR
export DEB_BUILD_OPTIONS="$DEB_BUILD_OPTIONS"
dpkg-buildpackage $ARCH_OPTIONS -b -us -uc -rfakeroot
