#!/bin/sh -e

# Install listed packages
SUDO='/usr/local/bin/sudo '
PKG='/usr/local/sbin/pkg '

if [ $# -eq 0 ]
then
    echo "Usage: $0 <pkgfile> [<pkgfile ...]"
    exit 42
fi

for pkg in "$@"
do
    if [ -r "${pkg}" ]
    then
        PKG_NAME=`/usr/local/sbin/pkg query -F ${pkg} '%n-%v'`

        if pkg info -q ${PKG_NAME}
        then
            ${SUDO} ${PKG} delete -qy ${PKG_NAME}
        fi

        ${SUDO} ${PKG} install -U -qy  ${pkg}
    else
        PKG_NAME=''
    fi

done
