#!/bin/sh -xe

case `dirname "$0"` in
  .)
    SCRIPTDIR=`pwd`;;
  *)
    case "$0" in
      /*) SCRIPTDIR=`dirname "$0"`;;
      *) SCRIPTDIR=`pwd`/`dirname "$0"`;;
    esac;;
esac

BASEDIR=`dirname "$SCRIPTDIR"`
BASEDIR=`dirname "$BASEDIR"`

PATH="$PATH:$SCRIPTDIR"

PKGNAME="$1"
TESTS="$2"
TARGET="$3"
OPTIMIZE="$4"
DEBUGSYM="$5"
VERSION="$6"

if [ "$TARGET" != "native" ]; then
  echo "Egh? Cross-compiling for Solaris!?"
  exit 42
fi

P=$BASEDIR/buildscripts/deps-packaging/$PKGNAME
PKGDIR=$BASEDIR/$PKGNAME/pkg
PREFIX=$BUILDPREFIX

rm -rf $PKGDIR
mkdir -p $PKGDIR

pkg-get-src "$P" | while read srcfile opts; do
  case "$srcfile" in
    *.gz|*.tgz)
      UNCOMPRESS="gzip -dc";;
    *.bz2)
      UNCOMPRESS=bzcat;;
    *.xz)
      UNCOMPRESS=xzcat;;
    *)
      echo "Unknown compression: $srcfile"
      exit 42;;
  esac

  if [ x$opts = xsubdir ]; then
    $UNCOMPRESS $srcfile | (cd $PKGDIR; tar xf -) || false
  else
    TD=/tmp/`basename $srcfile`.$$
    mkdir -p "$TD"
    $UNCOMPRESS $srcfile | (cd "$TD" && tar xf -) || false
    mv $TD/*/* $PKGDIR
    rm -r "$TD"
  fi
done
cp -R $P/* $PKGDIR

ARCH=`uname -m`

(cd $PKGDIR; BUILD_ROOT=$PKGDIR/out TESTS=$TESTS OPTIMIZE=$OPTIMIZE DEBUGSYM=$DEBUGSYM $P/hpux/build) || false

for package in `cat $P/hpux/packages`; do
  echo "Building $package"

  case $package in
    *-devel)
      cd $PKGDIR/out/$package$PREFIX/
      $BASEDIR/buildscripts/deps-packaging/psf.pl include $package $VERSION > $package.psf
      /usr/sbin/swpackage -s $PWD/$package.psf -x media_type=tape @ $BASEDIR/$PKGNAME/$package.depot
      cd $PKGDIR
      ;;
    *)
      cd $PKGDIR/out/$package$PREFIX/
      $BASEDIR/buildscripts/deps-packaging/psf.pl lib $package $VERSION > $package.psf
      /usr/sbin/swpackage -s $PWD/$package.psf -x media_type=tape @ $BASEDIR/$PKGNAME/$package.depot
      cd $PKGDIR
      ;;
  esac
done
