#!/usr/xpg4/bin/sh -xe

gen_prototype() {
  package="$1"
  pkgdir="$PKGDIR/out/$package/"
  echo "i pkginfo=$BASEDIR/$PKGNAME/$package.pkginfo"
  for f in `find $pkgdir`; do
    destf=/${f#$pkgdir}
    if [ "$destf" = "/" ]; then
      continue
    elif [ "$destf" = "/var" ]; then
      continue
    elif [ -f $f ] && [ -x $f ]; then
      echo "f none /$destf=$f 0755 root root"
    elif [ -f $f ]; then
      echo "f none /$destf=$f 0644 root root"
    elif [ -d $f ]; then
      echo "d none /$destf=$f 0755 root root"
    elif [ -h $f ]; then
      dest=`LANG= file -h $f | sed -e 's/.*symbolic link to //'`
      echo "s none /$destf=$dest root root"
    else
      echo "Unknown file type: $f" >&2
      exit 42
    fi
  done
}

case `dirname "$0"` in
  .)
    SCRIPTDIR=`pwd`;;
  *)
    case "$0" in
      /*) SCRIPTDIR=`dirname "$0"`;;
      *) SCRIPTDIR=`pwd`/`dirname "$0"`;;
    esac;;
esac

BASEDIR=`dirname "$SCRIPTDIR"`
BASEDIR=`dirname "$BASEDIR"`

PATH="$PATH:$SCRIPTDIR"

PKGNAME="$1"
TESTS="$2"
TARGET="$3"
OPTIMIZE="$4"
DEBUGSYM="5"
VERSION="$6"


if [ "$TARGET" != "native" ]; then
  echo "Egh? Cross-compiling for Solaris!?"
  exit 42
fi

P=$BASEDIR/buildscripts/deps-packaging/$PKGNAME
PKGDIR=$BASEDIR/$PKGNAME/pkg

rm -rf $PKGDIR
mkdir -p $PKGDIR

if which gtar 2>&1 | grep '^/' >/dev/null; then
  TAR=gtar
else
  TAR=tar
fi

pkg-get-buildscripts-src "$P" | while read srcfile opts; do
  case "$srcfile" in
    *.gz|*.tgz)
      UNCOMPRESS=gzcat;;
    *.bz2)
      UNCOMPRESS=bzcat;;
    *)
      echo "Unknown compression: $srcfile"
      exit 42;;
  esac

  if [ x$opts = xsubdir ]; then
    $UNCOMPRESS $srcfile | (cd $PKGDIR; $TAR xf -) || false
  else
    TD=/tmp/`basename $srcfile`.$$
    mkdir -p "$TD"
    $UNCOMPRESS $srcfile | (cd "$TD" && $TAR xf -) || false
    mv $TD/*/* $PKGDIR
    rm -r "$TD"
  fi
done
cp -R $P/* $PKGDIR

ARCH=`uname -p`

(cd $PKGDIR; BUILD_ROOT=$PKGDIR/out TESTS=$TESTS OPTIMIZE=$OPTIMIZE DEBUGSYM=$DEBUGSYM $P/solaris/build) || false

for package in `cat $P/solaris/packages`; do
  echo "Building $package"

  echo "PKG=$package
NAME=$package
ARCH=$ARCH
VERSION=$VERSION
CATEGORY=application
CLASSES=none" > $BASEDIR/$PKGNAME/$package.pkginfo

  gen_prototype $package > $BASEDIR/$PKGNAME/$package.prototype

  pkgmk -o -f $BASEDIR/$PKGNAME/$package.prototype -d $BASEDIR/$PKGNAME

  pkgtrans -o -s $BASEDIR/$PKGNAME $BASEDIR/$PKGNAME/$package.pkg $package
done
