#!/bin/sh

# Installs given packages

if [ $# -eq 0 ]; then
  echo "Usage: $0 <pkg> [<pkg> ...]"
  exit 1
fi

for pkg in "$@"; do
  P_FILENAME=`basename $pkg`
  P_NAME=${P_FILENAME%.tbz}

  if pkg info ${P_NAME}; then
    sudo pkg delete ${P_NAME}
  fi

  sudo pkg add $pkg
done
