#!/bin/sh 

gen_filelist()
{
  package="$1"
  pkgdir="$PKGDIR/out/$package/"

  echo "@comment pkg-list, v 1.00 `date`"
  echo "@comment ORIGIN:sysutils/$package"
  for f in `find $pkgdir`; do
    if [ -f $f ]; then
      destf=${f#$pkgdir}
	  echo "$destf"
    fi
  done
}

case `dirname "$0"` in
  .)
    SCRIPTDIR=`pwd`;;
  *)
    case "$0" in
      /*) SCRIPTDIR=`dirname "$0"`;;
      *) SCRIPTDIR=`pwd`/`dirname "$0"`;;
    esac;;
esac

BASEDIR=`dirname "$SCRIPTDIR"`
BASEDIR=`dirname "$BASEDIR"`

PATH="$PATH:$SCRIPTDIR"

PKGNAME="$1"
TESTS="$2"
TARGET="$3"
VERSION="$4"

P=$BASEDIR/buildscripts/deps-packaging/$PKGNAME
PKGDIR=$BASEDIR/$PKGNAME/pkg

rm -rf $PKGDIR
mkdir -p $PKGDIR

pkg-get-src "$P" | while read srcfile opts; do
  case "$srcfile" in
    *.gz|*.tgz)
      UNCOMPRESS="gzip -dc";;
    *.bz2)
      UNCOMPRESS=bzcat;;
    *)
      echo "Unknown compression: $srcfile"
      exit 42;;
  esac

  if [ x$opts = xsubdir ]; then
    $UNCOMPRESS $srcfile | (cd $PKGDIR; tar xf -) || false
  else
    TD=/tmp/`basename $srcfile`.$$
    mkdir -p "$TD"
    $UNCOMPRESS $srcfile | (cd "$TD" && tar xf -) || false
    mv $TD/*/* $PKGDIR
    rm -r "$TD"
  fi
done

cp -R $P/* $PKGDIR

ARCH=`uname -p`

(cd $PKGDIR; BUILD_ROOT=$PKGDIR/out TESTS=$TESTS $P/freebsd/build) || false

for package in `cat $P/freebsd/packages`; do
  echo "$package: dependency of CFEngine Nova.
version of $package: $VERSION
architecture of $package: $ARCH" > $BASEDIR/$PKGNAME/$package-comment

  echo "$package: created by buildscripts system" > $BASEDIR/$PKGNAME/$package-descr

  gen_filelist $package > $BASEDIR/$PKGNAME/$package-plist

  /usr/sbin/pkg create -j -f $BASEDIR/$PKGNAME/$package-plist -c $BASEDIR/$PKGNAME/$package-comment -d $BASEDIR/$PKGNAME/$package-descr -p $BASEDIR/$PKGNAME/pkg/out/$package/ $BASEDIR/$PKGNAME/$package-$VERSION-$ARCH.tbz

  cd $BASEDIR/$PKGNAME/

  echo "`pwd`"

  tar xvf $package-$VERSION-$ARCH.tbz

  head -n 2 ./+CONTENTS > plist-head
  sed '1,3d' ./+CONTENTS > tmp
  rm ./+CONTENTS
  cat plist-head > CONTENTS
  echo "@cwd /" >> CONTENTS
  cat tmp >> CONTENTS
  rm plist-head tmp
  mv CONTENTS ./+CONTENTS
  tar cjvf $package-$VERSION-$ARCH.tbz +CONTENTS +DESC +COMMENT var/
done
