#!/usr/xpg4/bin/sh -xe

gen_prototype() {
  package="$1"
  pkgdir="$PKGDIR/out/$package/"
  echo "i pkginfo=$BASEDIR/$PKGNAME/$package.pkginfo"
  # $BUILDPREFIX is usually /var/cfengine or /usr/localcw/opt/cfengine. Its
  # parent directories are usually provided by some other package, so adding
  # them to our package causes these packages to conflict, and we don't want
  # that. Hence, we need to exlude them. To do that, we find the parent dir for
  # $BUILDPREFIX:
  PREPREFIX=${BUILDPREFIX%/*}
  # (for example, it can be /usr/localcw/opt) and exclude all dirs that are in
  # its name - for example, /usr and /usr/localcw.
  for f in `find $pkgdir`; do
    destf=/${f#$pkgdir}
    # To check if $destf is substring of $PREPREFIX (or rather if $PREPREFIX
    # starts with $destf), we extract first N characters from $PREPREFIX, where
    # N is length of $destf, i.e. ${#destf}
    if [ "$(echo "$PREPREFIX" | cut -c 1-${#destf})" = "$destf" ]; then
      # $PREPREFIX starts from $destf, so it should be excluded
      continue
    elif [ -h $f ]; then
      dest=`LANG= file -h $f | sed -e 's/.*symbolic link to //'`
      echo "s none /$destf=$dest root root"
    elif [ -f $f ] && [ -x $f ]; then
      echo "f none /$destf=$f 0755 root root"
    elif [ -f $f ]; then
      echo "f none /$destf=$f 0644 root root"
    elif [ -d $f ]; then
      echo "d none /$destf=$f 0755 root root"
    else
      echo "Unknown file type: $f" >&2
      exit 42
    fi
  done
}

case `dirname "$0"` in
  .)
    SCRIPTDIR=`pwd`;;
  *)
    case "$0" in
      /*) SCRIPTDIR=`dirname "$0"`;;
      *) SCRIPTDIR=`pwd`/`dirname "$0"`;;
    esac;;
esac

BASEDIR=`dirname "$SCRIPTDIR"`
BASEDIR=`dirname "$BASEDIR"`

PATH="$PATH:$SCRIPTDIR"

PKGNAME="$1"
TESTS="$2"
TARGET="$3"
OPTIMIZE="$4"
DEBUGSYM="5"
VERSION="$6"


if [ "$TARGET" != "native" ]; then
  echo "Egh? Cross-compiling for Solaris!?"
  exit 42
fi

P=$BASEDIR/buildscripts/deps-packaging/$PKGNAME
PKGDIR=$BASEDIR/$PKGNAME/pkg

rm -rf $PKGDIR
mkdir -p $PKGDIR

if which gtar 2>&1 | grep '^/' >/dev/null; then
  TAR=gtar
else
  TAR=tar
fi

pkg-get-src "$P" | while read srcfile opts; do
  case "$srcfile" in
    *.gz|*.tgz)
      UNCOMPRESS="gzip -dc";;
    *.bz2)
      UNCOMPRESS=bzcat;;
    *.xz)
      UNCOMPRESS=xzcat;;
    *)
      echo "Unknown compression: $srcfile"
      exit 42;;
  esac

  if [ x$opts = xsubdir ]; then
    $UNCOMPRESS $srcfile | (cd $PKGDIR; $TAR xf -) || true
  else
    TD=/tmp/`basename $srcfile`.$$
    mkdir -p "$TD"
    $UNCOMPRESS $srcfile | (cd "$TD" && $TAR xf -) || true
    mv $TD/*/* $PKGDIR
    rm -r "$TD"
  fi
done
cp -R $P/* $PKGDIR

ARCH=`uname -p`

(cd $PKGDIR; BUILD_ROOT=$PKGDIR/out TESTS=$TESTS OPTIMIZE=$OPTIMIZE DEBUGSYM=$DEBUGSYM $P/solaris/build) || false

for package in `cat $P/solaris/packages`; do
  echo "Building $package"

  echo "PKG=$package
NAME=$package
ARCH=$ARCH
VERSION=$VERSION
CATEGORY=application
CLASSES=none" > $BASEDIR/$PKGNAME/$package.pkginfo

  gen_prototype $package > $BASEDIR/$PKGNAME/$package.prototype

  pkgmk -o -f $BASEDIR/$PKGNAME/$package.prototype -d $BASEDIR/$PKGNAME

  pkgtrans -o -s $BASEDIR/$PKGNAME $BASEDIR/$PKGNAME/$package.pkg $package
done
