#!/bin/sh

# This is a utility that caches things, both locally and in our own SFTP
# server (using the cache-sftp command). It can cache two kinds of
# things:
#
# - files: any single file can be cached with the commands "putfile" and
#       "listfile", and it's mostly used for source tarballs, to avoid
#       hitting upstream all the time.
#
# - packages: any directory can be cached using the commands "putpkg"
#       and "listpkgfiles", and it's mostly used for built
#       dependencies. Therefore the cached packages are stored into a
#       jenkins-label (i.e. architecture specific) named directory, to
#       avoid conflicts with same packages built on other systems.


. `dirname "$0"`/../build-scripts/functions

set -e
#set -x                                                  # for debugging

PATH=$PATH:$BASEDIR/buildscripts/deps-packaging         # for cache-sftp
MYNAME=`basename $0`

# Set to anything except "no" if you want to skip remote cache
CACHE_IS_ONLY_LOCAL=${CACHE_IS_ONLY_LOCAL:-no}

# Check for Jenkins node label and use that as index.
# JOB_BASE_NAME is something like label=PACKAGES_HUB_x86_64_linux_debian_7
label=${JOB_BASE_NAME#*=}
if [ x"$label" = x ]
then
    echo "Jenkins has not assigned a LABEL to this node," \
         "you are probably building manually;" \
         "disabling remote sftp cache"  1>&2
    label=NO_LABEL
    CACHE_IS_ONLY_LOCAL=yes
fi

CACHEDIR=$HOME/.cache/buildscripts_cache
# Binary packages are architecture (label) specific so they need a label subdir
PKGS_CACHEDIR=$CACHEDIR/pkgs
# Source tarballs etc are not
FILES_CACHEDIR=$CACHEDIR/files
# Make sure that we don't write directly to CACHEDIR but to the subdirs mentioned above
unset CACHEDIR

mkdir -p $PKGS_CACHEDIR
mkdir -p $FILES_CACHEDIR
[ -d $PKGS_CACHEDIR ]  ||  fatal "$MYNAME: cache directory does not exist: $PKGS_CACHEDIR"
[ -d $FILES_CACHEDIR ] ||  fatal "$MYNAME: cache directory does not exist: $FILES_CACHEDIR"

exit_usage()
{
    exec >&2
    echo "$MYNAME listpkgfiles  <pkg>-<version>"
    echo "    lists the full local paths to all files of that package found in cache"
    echo "    if necessary it fetches them from the sftp cache first"
    echo "$MYNAME putpkg  <pkg>-<version> <pkgfiles>..."
    # TODO decide to overwrite or not? probably yes...
    echo "    writes all pkgfiles to the local and remote cache; TODO OVERWRITE OR NOT?"
    echo "$MYNAME listfile  <filename>"
    echo "    given a filename without slashes, the output is the local full"
    echo "    pathname after it's fetched from remote, if needed"
    echo "$MYNAME putfile  <filename>"
    echo "    Stores a file locally and remotely"
    echo "$MYNAME keep_newest <number>"
    echo "    Keeps only <number> of packages in the local cache"

    exit 2
}

# Remove directory silently, if empty or with bogus, unimportant
# contents (having no files but only subdirs is also considered bogus,
# the subdir could be just the temporary transfer dir from a previous
# transfer).
rmdir_if_bogus()
{
(                                     # subshell to undo sh -x verbosity
    bogus=yes
    for f in "$1"/*
    do
        # if we find a non-empty file, then we are good
        if [ -f "$f" ]  &&  [ -s "$f" ]
        then
            bogus=no
            break
        fi
    done

    [ $bogus = yes ]  &&  [ -d "$1" ]  &&  rm -rf "$1"  ||  true
)
}


retval=73                                       # failure by default

cmd=$1
shift

case "$cmd" in
putpkg)
    if [ x"$1" = x ]  ||  [ x"$2" = x ]  ||  echo "$1" | grep_q '[/ ]'
    then
        fatal  "$MYNAME $cmd:  requires one package name as argument with no slashes or spaces, and many file path arguments"
    fi
    pkgname=$1
    shift

    pkg_cache_dir="$PKGS_CACHEDIR/$label/$pkgname"

    # Remove bogus or empty dirs
    rmdir_if_bogus $pkg_cache_dir

    if [ -d "$pkg_cache_dir" ]
    then
        # TODO DECIDE if it's better to force copying always
        echo "$MYNAME $cmd: Skipping because package already exists in local cache:  $pkg_cache_dir"  1>&2
    else
        mkdir -p $pkg_cache_dir
        cp "$@" $pkg_cache_dir/

        if [ $CACHE_IS_ONLY_LOCAL = no ]
        then
            cache-sftp putdir  $label/$pkgname  "$@"
        fi
    fi
    ;;
listpkgfiles)
    if [ x"$1" = x ]  ||  [ x"$2" != x ]  ||  echo "$1" | grep_q '[/ ]'
    then
        fatal  "$MYNAME $cmd:  requires exactly one package name as argument with no slashes or spaces"
    fi
    pkgname="$1"
    pkg_cache_dir="$PKGS_CACHEDIR/$label/$pkgname"

    # Remove bogus or empty dirs
    rmdir_if_bogus $pkg_cache_dir

    if [ ! -d $pkg_cache_dir ] && [ $CACHE_IS_ONLY_LOCAL = no ]
    then
        mkdir -p $pkg_cache_dir
        cd $pkg_cache_dir
        cache-sftp getdir  $label/$pkgname
        cd -  >/dev/null
    fi

    rmdir_if_bogus $pkg_cache_dir

    [ -d $pkg_cache_dir ]  &&  echo  $pkg_cache_dir/*  ||  true
    ;;
putfile)
    cp  $1  $FILES_CACHEDIR

    if [ $CACHE_IS_ONLY_LOCAL = no ]
    then
        cache-sftp putfile $1
    fi
    ;;
listfile)
    if [ x"$1" = x ]  ||  [ x"$2" != x ]  ||  echo "$1" | grep_q /
    then
        fatal  "$MYNAME $cmd:  requires exactly one file name as argument with no slashes"
    fi
    filename="$1"

    rm_if_empty $FILES_CACHEDIR/$filename

    if [ ! -f $FILES_CACHEDIR/$filename ] && [ $CACHE_IS_ONLY_LOCAL = no ]
    then
        cd $FILES_CACHEDIR/
        cache-sftp getfile "$filename"
        cd -  >/dev/null
    fi

    [ -f $FILES_CACHEDIR/$filename ]  &&  echo $FILES_CACHEDIR/$filename  ||  true
    ;;
keep_newest)
    case "$1" in
        ''|*[!0-9]*)  fatal \
            "$MYNAME $cmd requires only one argument, must be a number, but got:  $1" ;;
    esac

    number=`expr $1 + 1`

    cd $FILES_CACHEDIR/
    for f in `ls -t  |  sed -n $number,'$'p`
    do
        if [ ! -f "$f" ]
        then
            log_info "$MYNAME $cmd: skipping invalid file:  $f"
        else
            if `ls -tu  |  head -$number  |  grep_q "$f"`
            then
                log_info "$MYNAME $cmd: skipping file because it has been recently accessed:  $f"
            else
                log_info "$MYNAME $cmd: deleting file:  $f"
                rm -f "$f"
            fi
        fi
    done
    cd -  >/dev/null

    cd $PKGS_CACHEDIR/$label/
    for f in `ls -t  |  sed -n $number,'$'p`
    do
        if [ ! -d "$f" ]  ||  [ "$f" = "." ]  ||  [ "$f" = ".." ]  ||  var_contains f /
        then
            log_info "$MYNAME $cmd: skipping invalid directory:  $f"
        else
            if `ls -tu  |  head -$number  |  grep_q "$f"`
            then
                log_info "$MYNAME $cmd: skipping directory because it has been recently accessed:  $f"
            else
                log_info "$MYNAME $cmd: deleting directory:  $f"
                rm -rf "$f"
            fi
        fi
    done

    cd -  >/dev/null
    ;;
*)
    exit_usage
    ;;
esac
