#!/usr/xpg4/bin/sh -e

#Options

PREFIX=/var/cfengine

LS=${BUILD_ROOT}/cfbuild-sasl2${PREFIX}
LSD=${BUILD_ROOT}/cfbuild-sasl2-devel${PREFIX}
export LDFLAGS="-Wl,-R/var/cfengine/lib -L/var/cfengine/lib"

#Patch
$PATCH -p1 < solaris-unistd.patch
#Configure

# Work around bug in ancient libtool: -R is not passed to the linker.
if [ -x /usr/ccs/bin/ld ]
then
    LD="/usr/ccs/bin/ld $LDFLAGS"
    export LD
fi

./configure --prefix=$PREFIX CPPFLAGS=-I/var/cfengine/include

#Build

$MAKE -C include
$MAKE -C lib

#Test

#Install

$MAKE -C include install DESTDIR=${BUILD_ROOT}/cfbuild-sasl2-devel
$MAKE -C lib install DESTDIR=${BUILD_ROOT}/cfbuild-sasl2-devel

#Package

rm -rf ${LSD}/etc
rm -rf ${LSD}/lib/*.a
rm -rf ${LSD}/lib/*.la

mkdir -p ${LS}/lib
mv ${LSD}/lib/*.so* ${LS}/lib

