#!/bin/sh -e

# Options

PREFIX=${BUILDPREFIX}

TT=${BUILD_ROOT}/cfbuild-leech${PREFIX}
TTD=${BUILD_ROOT}/cfbuild-leech-devel${PREFIX}

# Build

# Touch this file, or else autoreconf is called for some reason
touch config.h.in
./configure --prefix=$PREFIX
gmake

# Test

# Install

mkdir -p $TTD/lib
mkdir -p $TTD/include
gmake install prefix=${TTD}

# Package

mkdir -p ${TT}/lib
mv ${TTD}/lib/libyaml.so* ${TT}/lib
