#!/bin/sh -e

# Options

PREFIX=${BUILDPREFIX}

TT=${BUILD_ROOT}/cfbuild-libcurl${PREFIX}
TTD=${BUILD_ROOT}/cfbuild-libcurl-devel${PREFIX}

# Build

# autotools on hpux 11.23 with gcc 4.2.3 uses -std=gnu99 which excludes _LARGEFILE_SOURCE required for fseeko()
# see https://www.gnu.org/software/libc/manual/html_node/Feature-Test-Macros.html for reference on _LARGEFILE_SOURCE

./configure --prefix=$PREFIX \
    --with-sysroot=$PREFIX \
    --with-ssl=$PREFIX \
    --with-zlib=$PREFIX \
    --disable-ldap \
    --disable-ldaps \
    --without-axtls \
    --without-cyassl \
    --without-egd-socket \
    --without-gnutls \
    --without-gssapi \
    --without-libidn \
    --without-libpsl \
    --without-librtmp \
    --without-libssh2 \
    --without-nghttp2 \
    --without-nss \
    --without-polarssl \
    --without-winidn \
    --without-winssl \
    CPPFLAGS="-DAF_LOCAL=AF_UNIX -D_LARGEFILE_SOURCE"
gmake

# Test

# Install

mkdir -p $TTD/lib
mkdir -p $TTD/include
gmake install prefix=${TTD}

# Package

rm -rf ${TTD}/man

mkdir -p ${TT}/lib
mv ${TTD}/lib/libcurl.so* ${TT}/lib
