#!/bin/sh

if [ -x /var/cfengine/bin/cf-key ]; then
        /var/cfengine/bin/cf-key
fi

STARTUP=/etc/init.d/cfengine3

if [ -f /etc/init.d/cfengine3 ];then
        for link in /etc/rc3.d/S97cfengine3 /etc/rc0.d/K05cfengine3 /etc/rc1.d/K05cfengine3 \
                /etc/rc2.d/K05cfengine3 /etc/rcS.d/K05cfengine3; do
                if [ ! -h $link ]; then
                        /usr/bin/ln -s $STARTUP $link
                fi
        done
fi

exit 0

