#!/bin/sh -e

# Options

PREFIX=${BUILDPREFIX}

OS=${BUILD_ROOT}/cfbuild-openssl${PREFIX}
OSD=${BUILD_ROOT}/cfbuild-openssl-devel${PREFIX}

# To pick up libgcc_s.so.1, which is apparently not in dyld path.
export LD_LIBRARY_PATH=$PREFIX/lib

# Patch
$PATCH -p1 < 0001-Don-t-use-__ATOMIC_ACQ_REL-on-older-compilers.patch
$PATCH -p1 < 0002-Cleanup-atomic-fallbacks-in-threads_pthread.c.patch

# Configure

$PERL ./Configure hpux-ia64-gcc $(<config_flags_$ROLE.txt) \
    $LDFLAGS --prefix=$PREFIX --libdir=lib

# Build

gmake depend
gmake

# Test

if [ "$TESTS" != no ]
then
    gmake test
fi

# Install

gmake DESTDIR=${BUILD_ROOT}/cfbuild-openssl-devel install_sw
gmake DESTDIR=${BUILD_ROOT}/cfbuild-openssl-devel install_ssldirs

# Package

rm -rf ${OSD}/bin
rm -rf ${OSD}/ssl
rm -rf ${OSD}/lib/engines
rm -rf ${OSD}/lib/fips*
rm -rf ${OSD}/lib/*.a
rm -rf ${OSD}/lib/cmake/OpenSSL

mkdir -p ${OS}/lib
mv ${OSD}/lib/libcrypto.so* ${OS}/lib
mv ${OSD}/lib/libssl.so* ${OS}/lib
mv ${OSD}/lib/ossl-modules ${OS}/lib/
