#!/bin/sh -e

# Options

PREFIX=/var/cfengine

OS=${BUILD_ROOT}/cfbuild-openssl${PREFIX}
OSD=${BUILD_ROOT}/cfbuild-openssl-devel${PREFIX}

# To pick up libgcc_s.so.1, which is apparently not in dyld path.
export LD_LIBRARY_PATH=$PREFIX/lib

# Configure

export PERL=$HOME/perl-my/bin/perl
$PERL ./Configure hpux-ia64-gcc shared  no-idea no-rc5 no-ssl2 no-ssl3 no-dtls no-psk no-srp \
    -D_GNU_SOURCE \
    --prefix=$PREFIX

# Build

gmake depend
gmake

# Test

if [ "$TESTS" != no ]
then
    gmake test
fi

# Install

gmake DESTDIR=${BUILD_ROOT}/cfbuild-openssl-devel install_sw

# Package

rm -rf ${OSD}/bin
rm -rf ${OSD}/ssl
rm -rf ${OSD}/lib/engines
rm -rf ${OSD}/lib/fips*
rm -rf ${OSD}/lib/*.a

mkdir -p ${OS}/lib
mv ${OSD}/lib/libcrypto.so* ${OS}/lib
mv ${OSD}/lib/libssl.so* ${OS}/lib

