#!/usr/xpg4/bin/sh -e

#Options

PREFIX=${BUILDPREFIX}

LI=${BUILD_ROOT}/cfbuild-libiconv${PREFIX}
LID=${BUILD_ROOT}/cfbuild-libiconv-devel${PREFIX}

#Patch

#Configure

./configure --prefix=$PREFIX CFLAGS=-I${PREFIX}/include

#Build

$MAKE 

#Test

#Install

sed -e"s/ \/usr\/local\/lib / /" libtool > libtool2
rm -f libtool
mv libtool2 libtool
$MAKE install DESTDIR=${BUILD_ROOT}/cfbuild-libiconv-devel

#Package

rm -rf ${LID}/lib/*.a
rm -rf ${LID}/lib/*.la

mkdir -p ${LI}/lib
mv ${LID}/lib/libiconv.so* ${LI}/lib
mv ${LID}/lib/libcharset.so* ${LI}/lib

