#!/bin/sh -e

# Options

PREFIX=${BUILDPREFIX}

TZ=${BUILD_ROOT}/cfbuild-zlib${PREFIX}
TZD=${BUILD_ROOT}/cfbuild-zlib-devel${PREFIX}

# Configure

./configure --prefix=${PREFIX}

#sed -e "s@TEST_LDFLAGS=@TEST_LDFLAGS=-Wl,-R${PREFIX}/lib @" < Makefile > Makefile.new
#mv Makefile.new Makefile

# Build

gmake

# Test

if [ "$TESTS" = all ]; then
  gmake check
fi

# Install

gmake install prefix=${TZD}

# Package

rm -f ${TZD}/lib/libz.a
rm -rf ${TZD}/share

mkdir -p ${TZ}/lib
mv ${TZD}/lib/libz.so* ${TZ}/lib

