#!/bin/sh -e

# Options

PREFIX=${BUILDPREFIX}

TT=${BUILD_ROOT}/cfbuild-diffutils${PREFIX}

# Build

./configure --prefix=$PREFIX
gmake

# Test

# Install

mkdir -p $TT/bin
gmake install prefix=${TT}

# Package

rm -rf $TT/share

