#!/usr/xpg4/bin/sh -e

# Options

PREFIX=${BUILDPREFIX}

TT=${BUILD_ROOT}/cfbuild-libcurl${PREFIX}
TTD=${BUILD_ROOT}/cfbuild-libcurl-devel${PREFIX}

# Build

./configure --prefix=$PREFIX \
    --with-sysroot=$PREFIX \
    --with-ssl=$PREFIX \
    --with-zlib=$PREFIX \
    --disable-ldap \
    --disable-ldaps \
    --without-gnutls \
    --without-gssapi \
    --without-libpsl \
    --without-librtmp \
    --without-libssh2 \
    --without-nghttp2 \
    --without-winidn \
    CPPFLAGS="-DAF_LOCAL=AF_UNIX"
$MAKE

# Test

# Install

mkdir -p $TTD/lib
mkdir -p $TTD/include
$MAKE install prefix=${TTD}

# Package

rm -rf ${TTD}/man

mkdir -p ${TT}/lib
mv ${TTD}/lib/libcurl.so* ${TT}/lib
