#!/usr/xpg4/bin/sh -e


# Options

PREFIX=${BUILDPREFIX}

# Package

#
# Gross hack, but what we could do?
#
if [ "$(uname -p)" = "sparc" ]; then
	# on 64-bit sparc CPUs, we take 64-bit library
	LIBGCC_LOC="/opt/csw/lib/sparcv9/"
else
	# on 32-bit Intel CPUs, we take 32-bit library
	LIBGCC_LOC="/opt/csw/lib/"
fi
mkdir -p ${BUILD_ROOT}/cfbuild-libgcc/${PREFIX}/lib
cp "$LIBGCC_LOC"libgcc_s.so.1 ${BUILD_ROOT}/cfbuild-libgcc/${PREFIX}/lib
