#!/usr/xpg4/bin/sh -e


# Options

PREFIX=${BUILDPREFIX}

# Package

#
# Gross hack, but what we could do?
#
LIBGCC_LOC="/opt/csw/lib/"
mkdir -p ${BUILD_ROOT}/cfbuild-libgcc/${PREFIX}/lib
cp "$LIBGCC_LOC"libgcc_s.so.1 ${BUILD_ROOT}/cfbuild-libgcc/${PREFIX}/lib
