#!/bin/sh -e

#Options

PREFIX=${BUILDPREFIX}

LS=${BUILD_ROOT}/cfbuild-sasl2${PREFIX}
LSD=${BUILD_ROOT}/cfbuild-sasl2-devel${PREFIX}

#Patch

#Configure

./configure --prefix=$PREFIX CPPFLAGS=-I${PREFIX}/include

#Build

gmake -C include
gmake -C common
gmake -C lib

#Test

#Install

gmake -C include install DESTDIR=${BUILD_ROOT}/cfbuild-sasl2-devel
gmake -C common install DESTDIR=${BUILD_ROOT}/cfbuild-sasl2-devel
gmake -C lib install DESTDIR=${BUILD_ROOT}/cfbuild-sasl2-devel

#Package

rm -rf ${LSD}/etc
rm -rf ${LSD}/lib/*.a
rm -rf ${LSD}/lib/*.la

mkdir -p ${LS}/lib
mv ${LSD}/lib/libsasl2* ${LS}/lib

