#!/bin/sh -e

# Options

PREFIX=/var/cfengine

QD=${BUILD_ROOT}/cfbuild-qdbm${PREFIX}
QDD=${BUILD_ROOT}/cfbuild-qdbm-devel${PREFIX}

# Patch

patch -p1 < hp-ux.patch

# Configure

./configure --prefix=$PREFIX

# Build

gmake

# Install

gmake install prefix=${QDD}

# Package

rm -f ${PREFIX}/bin/cb*
rm -f ${PREFIX}/bin/cr*
rm -f ${PREFIX}/bin/h*
rm -f ${PREFIX}/bin/o*
rm -f ${PREFIX}/bin/r*
rm -f ${PREFIX}/bin/v*
rm -f ${PREFIX}/bin/q*
rm -f ${PREFIX}/bin/dptest

rm -rf ${PREFIX}/lib/pkgconfig
rm -f ${PREFIX}/lib/libqdbm.a

rm -rf ${PREFIX}/man
rm -rf ${PREFIX}/share

mkdir -p ${QD}/bin ${QD}/lib
mv ${QDD}/bin/* ${QD}/bin
mv ${QDD}/lib/libqdbm.so* ${QD}/lib
