#!/usr/xpg4/bin/sh -e

# Options

PREFIX=${BUILDPREFIX}

PC=${BUILD_ROOT}/cfbuild-pcre2${PREFIX}
PCD=${BUILD_ROOT}/cfbuild-pcre2-devel${PREFIX}

# Configure

./configure --prefix=${PREFIX} --enable-shared --disable-static

# Build

$MAKE

# Test

if [ "$TESTS" = all ]; then
  $MAKE check
fi

# Install

$MAKE install DESTDIR=${BUILD_ROOT}/cfbuild-pcre2-devel

# Package

rm -f ${PCD}/bin/pcre2grep
rm -f ${PCD}/bin/pcre2test
rm -f ${PCD}/lib/*.la
rm -f ${PCD}/lib/libpcre2-posix.*
rm -f ${PCD}/lib/pkgconfig/libpcre2-posix.pc
rm -f ${PCD}/include/pcre2posix.h
rm -rf ${PCD}/share

mkdir -p ${PC}/lib
mv ${PCD}/lib/*.so* ${PC}/lib
