FROM debian:12-slim AS build

RUN apt update -y && apt upgrade -y
# cfengine dependencies
# CFEngine requires the ps command for processes promises
# CFEngine requires python for package promises package modules
# install ed to fix debian to conform better to standard: https://pubs.opengroup.org/onlinepubs/9799919799/utilities/ed.html
RUN apt install -y procps python3-minimal ed

COPY hub.deb /
# Only --unpack here to skip configuration which includes bringing up the database and webserver which might need to be reconfigured to use a higher port
# Using https_port 8443 and http_port 8080 in "developer" mode with docker requires the internal webserver to use the same ports as we don't support a mix
RUN dpkg --unpack hub.deb

# TODO: make optional: use my local development copy of masterfiles, easy to replace
RUN rm -rf /var/cfengine/share/NovaBase/masterfiles
# build shell script builds masterfiles to /tmp/masterfiles from $HOME/cfe/masterfiles
COPY mpf-build/ /var/cfengine/share/NovaBase/masterfiles/
# copy def.json to where dpkg --configure scripts copy it from
COPY def.json /var/cfengine/share/NovaBase/masterfiles/def.json

# post-build-setup.sh will finish the installation during the run step after the hostname has been set with docker run --hostname
COPY post-build-setup.sh /
CMD [ "sleep infinity" ]
