FROM debian:12-slim AS build
RUN apt update -y && apt upgrade -y
# cfengine dependencies
# CFEngine requires the ps command for processes promises
# CFEngine requires python for package promises package modules
# install ed to fix debian to conform better to standard: https://pubs.opengroup.org/onlinepubs/9799919799/utilities/ed.html
RUN apt install -y procps python3-minimal ed
COPY client.deb /
RUN dpkg -i client.deb
CMD [ "sleep infinity" ]
