#!/usr/xpg4/bin/sh -e

# Options

PREFIX=${BUILDPREFIX}

TT=${BUILD_ROOT}/cfbuild-libyaml${PREFIX}
TTD=${BUILD_ROOT}/cfbuild-libyaml-devel${PREFIX}

# Patch
# Solaris 8

# Build

./configure --prefix=$PREFIX

$MAKE

# Test

# Install

mkdir -p $TTD/lib
mkdir -p $TTD/include
$MAKE install prefix=${TTD}

# Package

rm -rf ${TTD}/man

mkdir -p ${TT}/lib
mv ${TTD}/lib/libyaml.so* ${TT}/lib
mv ${TTD}/lib/libyaml-0.so* ${TT}/lib
