#!/bin/sh -e

# Mirrors ../cfbuild-pcre2.spec (the actively maintained recipe used on
# Linux), adapted for macOS.

# Options

PREFIX=${BUILDPREFIX}

PC=${BUILD_ROOT}/cfbuild-pcre2${PREFIX}
PCD_ROOT=${BUILD_ROOT}/cfbuild-pcre2-devel
PCD=${PCD_ROOT}${PREFIX}

# Configure

./configure --prefix=${PREFIX} --enable-shared --disable-static

# Build

${MAKE:-make}

# Test intentionally skipped: TESTS=no on darwin (see compile-options).

# Install

${MAKE:-make} install DESTDIR=${PCD_ROOT}

# Package

rm -f ${PCD}/bin/pcre2grep
rm -f ${PCD}/bin/pcre2test
rm -f ${PCD}/lib/*.la
rm -f ${PCD}/lib/libpcre2-posix.*
rm -f ${PCD}/lib/pkgconfig/libpcre2-posix.pc
rm -f ${PCD}/include/pcre2posix.h
rm -rf ${PCD}/share

mkdir -p ${PC}/lib
mv ${PCD}/lib/*.dylib ${PC}/lib
