#!/bin/sh -e
 
# Options
PREFIX=${BUILDPREFIX:-/var/cfengine}

INSTALL_ROOT=${BUILD_ROOT}/cfbuild-apache

if [ -z "${MAKE}" ]
then
    export MAKE=`which gmake`
fi

if [ -z "{$CC}" ]
then
    # export CC=/usr/bin/cc
    export CC=`which gcc6`
    export GCC=`which gcc6`
fi

export CPPFLAGS="${CPPFLAGS} -I${PREFIX}/include -D_GNU_SOURCE"
export LDFLAGS="${LDFLAGS} -L${PREFIX}/lib -R${PREFIX}/lib"

# Configure
echo "LDFLAGS = '${LDFLAGS}'"
 
./configure --prefix=${PREFIX}/httpd \
            --enable-so \
            --enable-mods-shared="all ssl ldap authnz_ldap" \
            --with-z=${PREFIX} \
            --with-ssl=${PREFIX} \
            --with-ldap=${PREFIX} \
            --with-apr=${PREFIX} \
            --with-apr-util=${PREFIX} \
            --with-pcre=${PREFIX} \
            --with-mpm=prefork \
            CPPFLAGS="${CPPFLAGS}"
 
# Build
${MAKE}

# Install

${MAKE} install DESTDIR=${INSTALL_ROOT}

# Package
rm -rf ${INSTALL_ROOT}/${PREFIX}/httpd/man
rm -rf ${INSTALL_ROOT}/${PREFIX}/httpd/manual
rm -rf ${INSTALL_ROOT}/${PREFIX}/httpd/conf/httpd.conf
rm -rf ${INSTALL_ROOT}/${PREFIX}/httpd/conf/extra/httpd-ssl.conf
cp $(/usr/bin/dirname $0)/../httpd.conf ${INSTALL_ROOT}/${PREFIX}/httpd/conf/
