#!/bin/sh -e

# Options

LC=${BUILD_ROOT}/cfbuild-lcov/usr

# Install

gmake install DESTDIR=${BUILD_ROOT}/cfbuild-lcov 

# Package

rm -rf ${LC}/share/info
rm -rf ${LC}/share/emacs
rm -rf ${LC}/share/man
