#!/bin/sh

case $1 in 
	'start')
                ret=0
                if [ -x /usr/bin/zonename ];then
                        /usr/bin/pgrep -z `/usr/bin/zonename` cf-execd > /dev/null
                        ret=$?
                else
                        /usr/bin/pgrep cf-execd > /dev/null
                        ret=$?
                fi

                if [ $ret -gt 0 ];then
                        /var/cfengine/bin/cf-execd
                else
                        echo "cf-execd already running..."
                fi
		;;
	'stop')
		if [ -x /usr/bin/zonename ]; then
			for bin in cf-execd cf-monitord cf-serverd cf-agent cf-twin; do
				/usr/bin/pkill -TERM -z `zonename` $bin
			done
		else
			for bin in cf-execd cf-monitord cf-serverd cf-agent cf-twin; do
				/usr/bin/pkill -TERM $bin
        		done
		fi
		;;
	*)
		echo "Usage: $0 { start | stop }"
		exit 1
		;;
esac    
