#!/bin/sh

case "$1" in
start )
	ps -ef | grep -v grep | grep cf-execd > /dev/null
	ret=$?
	if [ $ret -gt 0 ]; then
		/var/cfengine/bin/cf-execd
	fi
        ;;
stop )
	PID=$$
	for i in cf-execd cf-serverd cf-monitord cf-hub; do
		ps -ef | grep $i | grep -v grep | awk '{print $2}' >> /tmp/cfengine3.$PID
	done
	while read line; do
		kill $line
	done < /tmp/cfengine3.$PID
	rm /tmp/cfengine3.$PID
        ;;
* )
        echo "Usage: $0 (start | stop)"
        exit 1
esac


