#!/bin/sh

if [ -x /usr/bin/zonename ]; then
        for bin in cf-execd cf-monitord cf-serverd cf-agent cf-hub; do
                /usr/bin/pkill -TERM -z `/usr/bin/zonename` $bin
        done
else
        for bin in cf-execd cf-monitord cf-serverd cf-agent cf-hub; do
                /usr/bin/pkill -TERM $bin
        done
fi

/usr/bin/rm -f /etc/rc3.d/S97cfengine3 /etc/rc0.d/K05cfengine3 /etc/rc1.d/K05cfengine3 \
        /etc/rc2.d/K05cfengine3 /etc/rcS.d/K05cfengine3 

