#!/bin/sh

if [ -x /usr/bin/zonename ]; then
        for bin in cf-execd cf-monitord cf-serverd cf-agent cf-hub; do
                /usr/bin/pkill -TERM -z `/usr/bin/zonename` $bin
        done
else
        for bin in cf-execd cf-monitord cf-serverd cf-agent cf-hub; do
                /usr/bin/pkill -TERM $bin
        done
fi

/usr/bin/rm -f /etc/rc3.d/S97cfengine3 /etc/rc0.d/K05cfengine3 /etc/rc1.d/K05cfengine3 \
        /etc/rc2.d/K05cfengine3 /etc/rcS.d/K05cfengine3

if [ -d /usr/local/sbin ]; then
        rm -f /usr/local/sbin/cf-agent /usr/local/sbin/cf-execd \
        /usr/local/sbin/cf-key /usr/local/sbin/cf-know /usr/local/sbin/cf-monitord \
        /usr/local/sbin/cf-promises /usr/local/sbin/cf-report /usr/local/sbin/cf-runagent \
        /usr/local/sbin/cf-serverd /usr/local/sbin/cf-twin /usr/local/sbin/cf-hub > /dev/null 2>&1
fi
