#!/usr/xpg4/bin/sh -e

# Options

PREFIX=/var/cfengine

TT=${BUILD_ROOT}/cfbuild-lmdb${PREFIX}
TTD=${BUILD_ROOT}/cfbuild-lmdb-devel${PREFIX}
export LDFLAGS="-Wl,-R/var/cfengine/lib -L/var/cfengine/lib"

# Patch
# Solaris 8

cd libraries/liblmdb && $PATCH -p3 < ../../mdb.patch && cd -
cd libraries/liblmdb && $PATCH -p3 < ../../mdb-robust.patch && cd -
cd libraries/liblmdb && $PATCH -p3 < ../../mdb.patch.sun && cd -

# Configure

# Build

cd libraries/liblmdb && $MAKE && cd -

# Test

# Install

mkdir -p $TTD/bin
mkdir -p $TTD/lib
mkdir -p $TTD/include
mkdir -p $TTD/man/man1
cd libraries/liblmdb && $MAKE install prefix=${TTD} && cd -

# Package

rm -rf ${TTD}/man

mkdir -p ${TT}/bin ${TT}/lib
mv ${TTD}/bin/* ${TT}/bin
mv ${TTD}/lib/liblmdb.so* ${TT}/lib
