#!/usr/xpg4/bin/sh -e

# Options

PREFIX=/var/cfengine

TT=${BUILD_ROOT}/cfbuild-lmdb${PREFIX}
TTD=${BUILD_ROOT}/cfbuild-lmdb-devel${PREFIX}

# Patch
# Solaris 8

for i in 00*.patch; do
    $PATCH -p1 < $i
done

$PATCH -p1 < mdb.patch.sun

# Configure

# Build

cd libraries/liblmdb
sh ./configure --prefix=$PREFIX
$MAKE
cd -

# Test

# Install

mkdir -p $TTD/bin
mkdir -p $TTD/lib
mkdir -p $TTD/include
mkdir -p $TTD/man/man1
cd libraries/liblmdb
$MAKE install prefix=${TTD}
cd -

# Package

rm -rf ${TTD}/man

mkdir -p ${TT}/bin ${TT}/lib
mv ${TTD}/bin/* ${TT}/bin
mv ${TTD}/lib/liblmdb.so* ${TT}/lib
