#!/usr/xpg4/bin/sh -e

# Options

PREFIX=${BUILDPREFIX}

TT=${BUILD_ROOT}/cfbuild-lmdb${PREFIX}
TTD=${BUILD_ROOT}/cfbuild-lmdb-devel${PREFIX}

# Patch
# Solaris 8

for i in 00*.patch
do
    $PATCH -p1 < $i
done

$PATCH -p1 < mdb.patch.sun

cd libraries/liblmdb

# Workaround for automake being sensitive to the order in which the generated
# files are applied. If Makefile.in is patched before aclocal.m4 (which it is,
# following natural file order), then it will try to rebuild Makefile.in, which
# it can't without automake. Work around it by touching that file.
touch Makefile.in

CONFIG_SHELL=/usr/xpg4/bin/sh sh ./configure --prefix=$PREFIX
$MAKE
cd -

# Test

# Install

mkdir -p $TTD/bin
mkdir -p $TTD/lib
mkdir -p $TTD/include
mkdir -p $TTD/man/man1
cd libraries/liblmdb
$MAKE install prefix=${TTD}
cd -

# Package

rm -rf ${TTD}/man

mkdir -p ${TT}/bin ${TT}/lib
mv ${TTD}/bin/* ${TT}/bin
mv ${TTD}/lib/liblmdb.so* ${TT}/lib
