#!/bin/sh -e

# Options

PREFIX=${BUILDPREFIX:-/var/cfengine}

INSTALL_ROOT=${BUILD_ROOT}/cfbuild-openldap

if [ -z "${MAKE}" ]
then
    MAKE=`which gmake`
fi

export CC=/usr/local/bin/gcc6
export GCC=/usr/local/bin/gcc6
export CPPFLAGS="${CPPFLAGS} -I${BUILD_ROOT}/include -I${PREFIX}/include -D_GNU_SOURCE"
export LDFLAGS="${LDFLAGS} -L${BUILD_ROOT}/lib -L${PREFIX}/lib -rpath=${PREFIX}/lib"

# Patch

# Patch configure to get around it confusing
# FreeBSD 11.1-RELEASE for FreeBSD 1 (which didn't do shared objects)
# I don't think FreeBSD 1 is a concern anymore.
/usr/bin/sed -i '' \
             -e 's/freebsd1\*)/freebsd1.*)/' \
             -e 's/freebsd1\*)/freebsd1.*)/' \
             -e 's/freebsd2\*)/freebsd2.*)/' \
             -e 's/freebsd\[123\]\*)/freebsd[123].*)/' \
             configure

# Configure

./configure --prefix=$PREFIX \
            --enable-shared \
            --disable-slapd \
            --disable-backends \
            --disable-overlays \
            --with-tls=openssl \
            --without-cyrus-sasl \
            --without-fetch \
            --disable-monitor \
            --disable-bdb \
            --disable-relay \
            --disable-syncprov 

# Build

${MAKE} -s depend
${MAKE} -s -C include
${MAKE} -s -C libraries

# Test

# Install

${MAKE} -s -C include   install DESTDIR=${INSTALL_ROOT}
${MAKE} -s -C libraries install DESTDIR=${INSTALL_ROOT}

# Package
# rm -rf ${OLD}/etc
# rm -f ${OLD}/lib/*.a
# rm -f ${OLD}/lib/*.la

# mkdir -p ${OL}/lib
# mv ${OLD}/lib/*.so* ${OL}/lib

