#!/bin/sh -e

# Options

PREFIX=${BUILDPREFIX:-/var/cfengine}

TZ=${BUILD_ROOT}/cfbuild-zlib${PREFIX}
TZD=${BUILD_ROOT}/cfbuild-zlib-devel${PREFIX}

# Configure

CC=gcc6 ./configure --prefix=${PREFIX}

/usr/bin/sed -i '' -e "s@TEST_LDFLAGS=@TEST_LDFLAGS=-Wl,-R${PREFIX}/lib @" Makefile 

# Build

make CC=gcc6 -s

# Test

if [ "$TESTS" != no ]; then
    echo "Running tests"
    make -s check
fi

# Install

make -s install prefix=${TZD}
# Package

rm -f ${TZD}/lib/libz.a
rm -rf ${TZD}/share

mkdir -p ${TZ}/lib
mv ${TZD}/lib/libz.so* ${TZ}/lib
