#!/bin/sh -e

# Options

PREFIX=${BUILDPREFIX}

LX=${BUILD_ROOT}/cfbuild-libxml2${PREFIX}
LXD=${BUILD_ROOT}/cfbuild-libxml2-devel${PREFIX}
CPPFLAGS="-I${PREFIX}/include"

# Patch

# Configure

mv configure configure.bak
sed 's/ *-Wno-array-bounds//' configure.bak >configure
chmod a+x configure
./configure CPPFLAGS="$CPPFLAGS" --prefix=${PREFIX} --without-python --without-iconv --without-lzma --without-zlib --with-iso8859x

# Build

gmake

# Test

# Install

gmake install DESTDIR=${BUILD_ROOT}/cfbuild-libxml2-devel

# Package

rm -f ${LXD}/bin/xmlcatalog
rm -f ${LXD}/bin/xmllint
rm -f ${LXD}/lib/libxml2.a
rm -f ${LXD}/lib/libxml2.la
rm -f ${LXD}/lib/xml2Conf.sh
rm -rf ${LXD}/share

mkdir -p ${LX}/lib
mv ${LXD}/lib/*.so* ${LX}/lib
