#!/bin/sh
#
# cfengine3
# 
#
# Created by Nakarin Phooripoom on 22/6/2011.
# Copyright 2010 Cfengine AS. All rights reserved.
#
### BEGIN INIT INFO
# Provides:          cfengine3
# Required-Start:    $local_fs $remote_fs $network $time
# Required-Stop:     $local_fs $remote_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: GNU configuration engine
# Description:       Tool for configuring and maintaining network machines
### END INIT INFO
#
# chkconfig: 2345 60 40
# description: Starts the cfengine daemons for remote and periodic \
#    execution of cfengine and for environment monitoring.
# set -e

##### start: Defined variables and conditios #####

CFEXECD=/var/cfengine/bin/cf-execd
CFSERVD=/var/cfengine/bin/cf-serverd
CFMOND=/var/cfengine/bin/cf-monitord

CFEXECD_PIDFILE=/var/cfengine/cf-execd.pid
CFSERVD_PIDFILE=/var/cfengine/cf-serverd.pid
CFMOND_PIDFILE=/var/cfengine/cf-monitord.pid

ECHO=/bin/echo
TOUCH=/bin/touch
RM=/bin/rm
KILL=/bin/kill
PKILL=/usr/bin/pkill

PATH=/sbin:/bin:/usr/sbin:/usr/bin:/var/cfengine/bin

# Has the package been 'removed' but not purged?
test -f $CFEXECD || exit 0

# defualt is no OS
SUSE=0
REDHAT=0
DEBIAN=0

# SuSE
if [ -f /usr/bin/zypper ]; then
	SUSE=1
else
	SUSE=0
fi

# RedHat4/RedHat5/CentOS/Fedora
if [ -f /usr/bin/yum ] || [ -f /usr/sbin/up2date ]; then
	REDHAT=1
else
	REDHAT=0
fi

# Debian/Ubuntu
if [ -f /usr/bin/apt-get ]; then
	DEBIAN=1
else
	DEBIAN=0
fi

# default control file
if [ "$DEBIAN" = "1" ]; then
	DEFAULT=/etc/default/cfengine3
else
	DEFAULT=/etc/sysconfig/cfengine3
fi
if [ -f $DEFAULT ]; then
	. $DEFAULT
else
	RUN_CF_EXECD=1
	RUN_CF_SERVERD=1
	RUN_CF_MONITORD=1
fi

# Check /sbin/startproc for SUSE
if [ -x /sbin/startproc ] && [ -f /etc/rc.status ]; then
	. /etc/rc.status
	rc_reset
	PROC=1
else
	PROC=0
fi

# Source function library. (Redhat/Centos/Fedora)
if [ -f /usr/bin/yum ] && [ -f /etc/rc.d/init.d/functions ]; then
	. /etc/rc.d/init.d/functions
	FUNC=1
else
	set -e
	FUNC=0
fi

# Check something for Debian/Ubuntu
if [ -x /sbin/start-stop-daemon ]; then
	SSD=1
else
	SSD=0
fi

# Grep PID
cfexecd_status=`ps waxu|grep -v grep|grep cf-execd|awk -F' ' '{print $2}'`
cfserverd_status=`ps waxu|grep -v grep|grep cf-serverd|awk -F' ' '{print $2}'`
cfmonitord_status=`ps waxu|grep -v grep|grep cf-monitord|awk -F' ' '{print $2}'`

##### end: Defined variables and conditions #####

### start scripting here ###

case "$1" in
	start)
		if ! [ -f /var/cfengine/inputs/promises.cf ]; then
			exit 0
		fi

		# start cf-execd
		# Redhat/Centos/Fedora
		if [ "$RUN_CF_EXECD" = "1" ] && [ "$REDHAT" = "1" ] && [ "$FUNC" = "1" ]; then
			$ECHO -n "Starting `basename $CFEXECD`: "
			daemon $CFEXECD
			$TOUCH /var/lock/subsys/`basename $CFEXECD`
			$ECHO
		elif [ "$RUN_CF_EXECD" = "1" ] && [ "$REDHAT" = "1" ] && [ "$FUNC" = "0" ]; then
			$ECHO -n "Starting `basename $CFEXECD`: "
			$CFEXECD
			$TOUCH /var/lock/subsys/`basename $CFEXECD`
			$ECHO
		fi
		# SUSE
		if [ "$RUN_CF_EXECD" = "1" ] && [ "$SUSE" = "1" ] && [ "$PROC" = "1" ]; then
			$ECHO -n "Starting `basename $CFEXECD`: "
			/sbin/startproc $CFEXECD
			rc_status -v
			$TOUCH /var/run/`basename $CFEXECD`.pid
		elif [ "$RUN_CF_EXECD" = "1" ] && [ "$SUSE" = "1" ] && [ "$PROC" = "0" ]; then
			$ECHO -n "Starting `basename $CFEXECD`: "
			$CFEXECD
			$TOUCH /var/run/`basename $CFEXECD`.pid
		fi
		# Debian/Ubuntu
		if [ "$RUN_CF_EXECD" = "1" ] && [ "$DEBIAN" = "1" ] && [ "$SSD" = "1" ]; then
			$ECHO -n "Starting `basename $CFEXECD`: "
			/sbin/start-stop-daemon --start --pidfile $CFEXECD_PIDFILE --verbose --exec $CFEXECD
			$TOUCH /var/lock/`basename $CFEXECD`
		elif [ "$RUN_CF_EXECD" = "1" ] && [ "$DEBIAN" = "1" ] && [ "$SSD" = "0" ]; then
			$ECHO -n "Starting `basename $CFEXECD`: "
			$CFEXECD
			$TOUCH /var/lock/`basename $CFEXECD`
			$ECHO
		fi
		
		# start cf-serverd
		# Redhat/Centos/Fedora
		if [ "$RUN_CF_SERVERD" = "1" ] && [ "$REDHAT" = "1" ] && [ "$FUNC" = "1" ]; then
			$ECHO -n "Starting `basename $CFSERVD`: "
			daemon $CFSERVD
			$TOUCH /var/lock/subsys/`basename $CFSERVD`
			$ECHO
		elif [ "$RUN_CF_SERVERD" = "1" ] && [ "$REDHAT" = "1" ] && [ "$FUNC" = "0" ]; then
			$ECHO -n "Starting `basename $CFSERVD`: "
			$CFSERVD
			$TOUCH /var/lock/subsys/`basename $CFSERVD`
			$ECHO
		fi
		# SUSE
		if [ "$RUN_CF_SERVERD" = "1" ] && [ "$SUSE" = "1" ] && [ "$PROC" = "1" ]; then
			$ECHO -n "Starting `basename $CFSERVD`: "
			/sbin/startproc $CFSERVD
			rc_status -v
			$TOUCH /var/run/`basename $CFSERVD`.pid
		elif [ "$RUN_CF_SERVERD" = "1" ] && [ "$SUSE" = "1" ] && [ "$PROC" = "0" ]; then
			$ECHO -n "Starting `basename $CFSERVD`: "
			$CFSERVD
			$TOUCH /var/run/`basename $CFSERVD`.pid
		fi
		# Debian/Ubuntu
		if [ "$RUN_CF_SERVERD" = "1" ] && [ "$DEBIAN" = "1" ] && [ "$SSD" = "1" ]; then
			$ECHO -n "Starting `basename $CFSERVD`: "
			/sbin/start-stop-daemon --start --pidfile $CFSERVD_PIDFILE --verbose --exec $CFSERVD
			$TOUCH /var/lock/`basename $CFSERVD`
		elif [ "$RUN_CF_SERVERD" = "1" ] && [ "$DEBIAN" = "1" ] && [ "$SSD" = "0" ]; then
			$ECHO -n "Starting `basename $CFSERVD`: "
			$CFSERVD
			$TOUCH /var/lock/`basename $CFSERVD`
			$ECHO
		fi
		
		# start cf-monitord
		# Redhat/Centos/Fedora
		if [ "$RUN_CF_MONITORD" = "1" ] && [ "$REDHAT" = "1" ] && [ "$FUNC" = "1" ]; then
			$ECHO -n "Starting `basename $CFMOND`: "
			daemon $CFMOND
			$TOUCH /var/lock/subsys/`basename $CFMOND`
			$ECHO
		elif [ "$RUN_CF_MONITORD" = "1" ] && [ "$REDHAT" = "1" ] && [ "$FUNC" = "0" ]; then
			$ECHO -n "Starting `basename $CFMOND`: "
			$CFMOND
			$TOUCH /var/lock/subsys/`basename $CFMOND`
			$ECHO
		fi
		# SUSE
		if [ "$RUN_CF_MONITORD" = "1" ] && [ "$SUSE" = "1" ] && [ "$PROC" = "1" ]; then
			$ECHO -n "Starting `basename $CFMOND`: "
			/sbin/startproc $CFMOND
			rc_status -v
			$TOUCH /var/run/`basename $CFMOND`.pid
		elif [ "$RUN_CF_MONITORD" = "1" ] && [ "$SUSE" = "1" ] && [ "$PROC" = "0" ]; then
			$ECHO -n "Starting `basename $CFMOND`: "
			$CFMOND
			$TOUCH /var/run/`basename $CFMOND`.pid
		fi
		# Debian/Ubuntu
		if [ "$RUN_CF_MONITORD" = "1" ] && [ "$DEBIAN" = "1" ] && [ "$SSD" = "1" ]; then
			$ECHO -n "Starting `basename $CFMOND`: "
			/sbin/start-stop-daemon --start --pidfile $CFMOND_PIDFILE --verbose --exec $CFMOND
			$TOUCH /var/lock/`basename $CFMOND`
		elif [ "$RUN_CF_MONTIROD" = "1" ] && [ "$DEBIAN" = "1" ] && [ "$SSD" = "0" ]; then
			$ECHO -n "Starting `basename $CFMOND`: "
			$CFMOND
			$TOUCH /var/lock/`basename $CFMOND`
			$ECHO
		fi
		exit 0
	;;
	stop)
		# shutdown cf-execd
		# Redhat/Centos/Fedora
		if [ "$RUN_CF_EXECD" = "1" ] && [ "$REDHAT" = "1" ] && [ "$FUNC" = "1" ]; then
			$ECHO -n "Shutting down `basename $CFEXECD`: "
			killproc $CFEXECD || :
			if [ -f /var/lock/subsys/`basename $CFEXECD` ]; then
				$RM -f /var/lock/subsys/`basename $CFEXECD` || true
			fi
			$ECHO
		elif [ "$RUN_CF_EXECD" = "1" ] && [ "$REDHAT" = "1" ] && [ "$FUNC" = "0" ]; then
			$ECHO -n "Shutting down `basename $CFEXECD`: "
			$PKILL `basename $CFEXECD` || :
			if [ -f /var/lock/subsys/`basename $CFEXECD` ]; then
				$RM -f /var/lock/subsys/`basename $CFEXECD` || true
			fi
			$ECHO
		fi
		# SUSE
		if [ "$RUN_CF_EXECD" = "1" ] && [ "$SUSE" = "1" ] && [ "$PROC" = "1" ]; then
			if [ $cfexecd_status ]; then
				$ECHO -n "Shutting down `basename $CFEXECD`: "
				/sbin/killproc -TERM $CFEXECD || :
				rc_status -v
				if [ -f /var/run/`basename $CFEXECD`.pid ]; then
					$RM /var/run/`basename $CFEXECD`.pid || true
				fi
			fi
		elif [ "$RUN_CF_EXECD" = "1" ] && [ "$SUSE" = "1" ] && [ "$PROC" = "0" ]; then
			if [ $cfexecd_status ]; then
				$ECHO -n "Shutting down `basename $CFEXECD`: "
				$PKILL `basename $CFEXECD` || :
				if [ -f /var/run/`basename $CFEXECD`.pid ]; then
					$RM /var/run/`basename $CFEXECD`.pid || true
				fi
			fi
		fi
		# Debian/Ubuntu
		if [ "$DEBIAN" = "1" ] && [ "$SSD" = "1" ]; then
			$ECHO -n "Shutting down `basename $CFEXECD` ... "
			/sbin/start-stop-daemon -o --stop --pidfile $CFEXECD_PIDFILE --retry 5 --name `basename $CFEXECD` || :
			if [ -f /var/lock/`basename $CFEXECD` ]; then
				$RM /var/lock/`basename $CFEXECD` || true
			fi
			$ECHO
		elif [ "$RUN_CF_EXECD" = "1" ] && [ "$DEBIAN" = "1" ] && [ "$SSD" = "0" ]; then
			if [ $cfexecd_status ]; then
				$ECHO -n "Shutting down `basename $CFEXECD` ... "
				$PKILL `basename $CFEXECD` || :
				if [ -f /var/lock/`basename $CFEXECD` ]; then
					$RM /var/lock/`basename $CFEXECD` || true
				fi
				$ECHO
			fi
		fi
		
		# shutdown cf-serverd
		# Redhat/Centos/Fedora
		if [ "$RUN_CF_SERVERD" = "1" ] && [ "$REDHAT" = "1" ] && [ "$FUNC" = "1" ]; then
			$ECHO -n "Shutting down `basename $CFSERVD`: "
			killproc $CFSERVD || :
			if [ -f /var/lock/subsys/`basename $CFSERVD` ]; then
				$RM -f /var/lock/subsys/`basename $CFSERVD` || true
			fi
			$ECHO
		elif [ "$RUN_CF_SERVERD" = "1" ] && [ "$REDHAT" = "1" ] && [ "$FUNC" = "0" ]; then
			$ECHO -n "Shutting down `basename $CFSERVD`: "
			$PKILL `basename $CFSERVD` || :
			if [ -f /var/lock/subsys/`basename $CFSERVD` ]; then
				$RM -f /var/lock/subsys/`basename $CFSERVD` || true
			fi
			$ECHO
		fi
		# SUSE
		if [ "$RUN_CF_SERVERD" = "1" ] && [ "$SUSE" = "1" ] && [ "$PROC" = "1" ]; then
			if [ $cfserverd_status ]; then
				$ECHO -n "Shutting down `basename $CFSERVD`: "
				/sbin/killproc -TERM $CFSERVD || :
				rc_status -v
				if [ -f /var/run/`basename $CFSERVD`.pid ]; then
					$RM /var/run/`basename $CFSERVD`.pid || true
				fi
			fi
		elif [ "$RUN_CF_SERVERD" = "1" ] && [ "$SUSE" = "1" ] && [ "$PROC" = "0" ]; then
			if [ $cfserverd_status ]; then
				$ECHO -n "Shutting down `basename $CFSERVD`: "
				$PKILL `basename $CFSERVD` || :
				if [ -f /var/run/`basename $CFSERVD`.pid ]; then
					$RM /var/run/`basename $CFSERVD`.pid || true
				fi
			fi
		fi
		# Debian/Ubuntu
		if [ "$DEBIAN" = "1" ] && [ "$SSD" = "1" ]; then
			$ECHO -n "Shutting down `basename $CFSERVD` ... "
			/sbin/start-stop-daemon -o --stop --pidfile $CFSERVD_PIDFILE --retry 5 --name `basename $CFSERVD` || :
			if [ -f /var/lock/`basename $CFSERVD` ]; then
				$RM /var/lock/`basename $CFSERVD` || true
			fi
			$ECHO
		elif [ "$RUN_CF_SERVERD" = "1" ] && [ "$DEBIAN" = "1" ] && [ "$SSD" = "0" ]; then
			if [ $cfserverd_status ]; then
				$ECHO -n "Shutting down `basename $CFSERVD` ... "
				$PKILL `basename $CFSERVD` || :
				if [ -f /var/lock/`basename $CFSERVD` ]; then
					$RM /var/lock/`basename $CFSERVD` || true
				fi
				$ECHO
			fi
		fi
		
		# shutdown cf-monitord
		# Redhat/Centos/Fedora
		if [ "$RUN_CF_MONITORD" = "1" ] && [ "$REDHAT" = "1" ] && [ "$FUNC" = "1" ]; then
			$ECHO -n "Shutting down `basename $CFMOND`: "
			killproc $CFMOND || :
			if [ -f /var/lock/subsys/`basename $CFMOND` ]; then
				$RM -f /var/lock/subsys/`basename $CFMOND` || true
			fi
			$ECHO
		elif [ "$RUN_CF_MONITORD" = "1" ] && [ "$REDHAT" = "1" ] && [ "$FUNC" = "0" ]; then
			$ECHO -n "Shutting down `basename $CFMOND`: "
			$PKILL `basename $CFMOND` || :
			if [ -f /var/lock/subsys/`basename $CFMOND` ]; then
				$RM -f /var/lock/subsys/`basename $CFMOND` || true
			fi
			$ECHO
		fi
		# SUSE
		if [ "$RUN_CF_MONITORD" = "1" ] && [ "$SUSE" = "1" ] && [ "$PROC" = "1" ]; then
			if [ $cfmonitord_status ]; then
				$ECHO -n "Shutting down `basename $CFMOND`: "
				/sbin/killproc -TERM $CFMOND || :
				rc_status -v
				if [ -f /var/run/`basename $CFMOND`.pid ]; then
					$RM /var/run/`basename $CFMOND`.pid || true
				fi
			fi
		elif [ "$RUN_CF_MONITORD" = "1" ] && [ "$SUSE" = "1" ] && [ "$PROC" = "0" ]; then
			if [ $cfmonitord_status ]; then
				$ECHO -n "Shutting down `basename $CFMOND`: "
				$PKILL `basename $CFMOND` || :
				if [ -f /var/run/`basename $CFMOND`.pid ]; then
					$RM /var/run/`basename $CFMOND`.pid || true
				fi
			fi
		fi
		# Debian/Ubuntu
		if [ "$DEBIAN" = "1" ] && [ "$SSD" = "1" ]; then
			$ECHO -n "Shutting down `basename $CFMOND` ... "
			/sbin/start-stop-daemon -o --stop --pidfile $CFMOND_PIDFILE --retry 5 --name `basename $CFMOND` || :
			if [ -f /var/lock/`basename $CFMOND` ]; then
				$RM /var/lock/`basename $CFMOND` || true
			fi
			$ECHO
		elif [ "$RUN_CF_MONITORD" = "1" ] && [ "$DEBIAN" = "1" ] && [ "$SSD" = "0" ]; then
			if [ $cfmonitord_status ]; then
				$ECHO -n "Shutting down `basename $CFMOND` ... "
				$PKILL `basename $CFMONITORD` || :
				if [ -f /var/lock/`basename $CFMOND` ]; then
					$RM /var/lock/`basename $CFMOND` || true
				fi
				$ECHO
			fi
		fi
                exit 0
	;;
	status)
		# status cf-execd
		# Redhat/Centos/Fedora
		if [ "$REDHAT" = "1" ] && [ "$FUNC" = "1" ]; then
			status $CFEXECD
		elif [ "$REDHAT" = "1" ] && [ "$FUNC" = "0" ]; then
			if [ $cfexecd_status ]; then
				$ECHO "cf-execd (pid $cfexecd_status) is running..."
			else 
				$ECHO "cf-execd is not running"
			fi
		fi
		# SUSE
		if [ "$RUN_CF_EXECD" = "1" ] && [ "$SUSE" = "1" ] && [ "$PROC" = "1" ]; then
			if [ $cfexecd_status ]; then
				$ECHO -n "Checking for `basename $CFEXECD` "
				checkproc $CFEXECD
				rc_status -v
			fi
		fi
		# Debain/Ubuntu
		if [ "$DEBIAN" = "1" ]; then
			if [ $cfexecd_status ]; then
				$ECHO "cf-execd (pid $cfexecd_status) is running..."
			else 
				$ECHO "cf-execd is not running"
			fi
		fi
		
		# status cf-serverd
		# Redhat/Centos/Fedora
		if [ "$REDHAT" = "1" ] && [ "$FUNC" = "1" ]; then
			status $CFSERVD
		elif [ "$REDHAT" = "1" ] && [ "$FUNC" = "0" ]; then
			if [ $cfserverd_status ]; then
				$ECHO "cf-serverd (pid $cfserverd_status) is running..."
			else
				$ECHO "cf-serverd is not running"
			fi
		fi
		# SUSE
		if [ "$RUN_CF_SERVERD" = "1" ] && [ "$SUSE" = "1" ] && [ "$PROC" = "1" ]; then
			if [ $cfserverd_status ]; then
				$ECHO -n "Checking for `basename $CFSERVD` "
				checkproc $CFSERVD
				rc_status -v
			fi
		fi
		# Debain/Ubuntu
		if [ "$DEBIAN" = "1" ]; then
			if [ $cfserverd_status ]; then
				$ECHO "cf-serverd (pid $cfserverd_status) is running..."
			else 
				$ECHO "cf-serverd is not running"
			fi
		fi
		
		# status cf-monitord
		# Redhat/Centos/Fedora
		if [ "$REDHAT" = "1" ] && [ "$FUNC" = "1" ]; then
			status $CFMOND
		elif [ "$REDHAT" = "1" ] && [ "$FUNC" = "0" ]; then
			if [ $cfmonitord_status ]; then
				$ECHO "cf-monitord (pid $cfmonitord_status) is running..."
			else
				$ECHO "cf-monitord is not running"
			fi
		fi
		# SUSE
		if [ "$RUN_CF_MONITORD" = "1" ] && [ "$SUSE" = "1" ] && [ "$PROC" = "1" ]; then
			if [ $cfmonitord_status ]; then
				echo -n "Checking for `basename $CFMOND` "
				checkproc $CFMOND
				rc_status -v
			fi
		fi
		# Debain/Ubuntu
		if [ "$DEBIAN" = "1" ]; then
			if [ $cfmonitord_status ]; then
				$ECHO "cf-monitord (pid $cfmonitord_status) is running..."
			else 
				$ECHO "cf-monitord is not running"
			fi
		fi
                exit 0
	;;
	restart|reload|force-reload)
		$0 stop
		$0 start
	;;
	*)
		N=/etc/init.d/cfengine3
		echo "Usage: $N {start|stop|status|restart|reload|force-reload}" >&2
		exit 1
	;;
esac
