#!/bin/sh

# Options

PREFIX=${BUILDPREFIX:-/var/cfengine}
INSTALL_ROOT=${BUILD_ROOT}/cfbuild-openssl${PREFIX}

if [ -z "$MAKE" ]
then
    export MAKE=`which make`
fi

# To pick up libgcc_s.so.1, which is apparently not in dyld path.
export LD_LIBRARY_PATH=$PREFIX/lib

# Patch
DEBUG_CONFIG_FLAGS=
DEBUG_CFLAGS=
if [ $BUILD_TYPE = "DEBUG" ]
then
    DEBUG_CONFIG_FLAGS="no-asm -DPURIFY"
    DEBUG_CFLAGS="-g2 -O1 -fno-omit-frame-pointer"
    # Workaround for OpenSSL build issue on our old SuSE buildslave, see:
    # http://www.mail-archive.com/openssl-dev@openssl.org/msg39231.html
elif [ "$OS" = sles ]
then
    DEBUG_CONFIG_FLAGS=no-asm
fi


# Configure


./config shared  no-idea no-rc5 no-ssl3 no-dtls no-psk no-srp no-engine \
         ${DEBUG_CONFIG_FLAGS} \
         --prefix=$PREFIX \
         ${DEBUG_CFLAGS} \
         ${LDFLAGS}

# Build
if [ $BUILD_TYPE = "DEBUG" ]
then
    sed -e '/^CFLAGS=/{s/ -O3//;s/ -fomit-frame-pointer//;}'   \
        Makefile > Makefile.cfe \
        && mv Makefile.cfe Makefile
fi

${MAKE} -s depend
${MAKE} -s

# Test

# ECDSA/ECDH tests are broken, so we explicitly omit them

if [ "$TESTS" != no ]; then
  make test TESTS="test_des test_idea test_sha test_md4 test_md5 test_hmac test_md2 test_mdc2 test_rmd test_rc2 test_rc4 test_rc5 test_bf test_cast test_aes test_rand test_bn test_ec test_enc test_x509 test_rsa test_crl test_sid test_gen test_req test_pkcs7 test_verify test_dh test_dsa test_ss test_ca test_engine test_evp test_ssl test_ige test_jpake"
fi

# Install

make DESTDIR=${INSTALL_ROOT%${PREFIX}} install_sw
make DESTDIR=${INSTALL_ROOT%${PREFIX}} install_ssldirs

# Package

# rm -rf ${OSD}/bin
# rm -rf ${OSD}/ssl
# rm -rf ${OSD}/lib/fips*
# rm -rf ${OSD}/lib/*.a

# mkdir -p ${OS}/lib
# mv ${OSD}/lib/libcrypto.so* ${OS}/lib
# mv ${OSD}/lib/libssl.so* ${OS}/lib
