#!/bin/sh -e

# Options

PREFIX=/var/cfengine

PC=${BUILD_ROOT}/cfbuild-pcre${PREFIX}
PCD=${BUILD_ROOT}/cfbuild-pcre-devel${PREFIX}

# HP-UX needs the .libs directory in the library search path because of a
# bug in libtool: it will specify libpcre.so.3 as the dependency of
# libpcreposix.so.3, however when it links it tries to link to libpcre.so.
# Although they are the same library, the native ld is not happy with this,
# and starts looking for the libpcre.so.3 library on its own, which it won't
# find, because it wasn't listed on the command line. Hence we need to
# specify libtool's secret library stash: ".libs".
LDFLAGS="$LDFLAGS -L.libs"

# Patch

# Configure

./configure --prefix=$PREFIX --enable-unicode-properties --disable-cpp

# Build

gmake

# Test

if [ "$TESTS" = all ]; then
  gmake check
fi

# Install

gmake install DESTDIR=${BUILD_ROOT}/cfbuild-pcre-devel

# Package

rm -f ${PCD}/bin/pcregrep
rm -f ${PCD}/bin/pcretest
rm -f ${PCD}/lib/*.a
rm -f ${PCD}/lib/*.la
rm -rf ${PCD}/share

mkdir -p ${PC}/lib
mv ${PCD}/lib/*.so* ${PC}/lib
