#!/usr/xpg4/bin/sh -e

# Options

PREFIX=${BUILDPREFIX}

OL=${BUILD_ROOT}/cfbuild-openldap${PREFIX}
OLD=${BUILD_ROOT}/cfbuild-openldap-devel${PREFIX}

# Patch

# Configure

./configure --prefix=$PREFIX --enable-shared --disable-slapd --disable-backends \
            --with-tls=openssl --without-gssapi \
            CPPFLAGS=-I$PREFIX/include \
            CC=gcc

# Build

$MAKE -C include
$MAKE -C libraries

# Test

# Install

$MAKE -C include install DESTDIR=${BUILD_ROOT}/cfbuild-openldap-devel
$MAKE -C libraries install DESTDIR=${BUILD_ROOT}/cfbuild-openldap-devel

# Package

rm -rf ${OLD}/etc
rm -f ${OLD}/lib/*.a
rm -f ${OLD}/lib/*.la

mkdir -p ${OL}/lib
mv ${OLD}/lib/*.so* ${OL}/lib
