#!/bin/sh -e

# Options

PREFIX=/var/cfengine

OL=${BUILD_ROOT}/cfbuild-openldap${PREFIX}
OLD=${BUILD_ROOT}/cfbuild-openldap-devel${PREFIX}

# Patch

# Configure

./configure --prefix=$PREFIX --enable-shared --disable-slapd --disable-backends \
            --with-tls=openssl --without-gssapi --without-threads \
            LDFLAGS="-L/var/cfengine/lib -L${OLD}/lib" CPPFLAGS=-I/var/cfengine/include

# Build

gmake -C include
gmake -C libraries

# Test

# Install

gmake -C include install DESTDIR=${BUILD_ROOT}/cfbuild-openldap-devel
gmake -C libraries install DESTDIR=${BUILD_ROOT}/cfbuild-openldap-devel

# Package

rm -rf ${OLD}/etc
rm -f ${OLD}/lib/*.a
rm -f ${OLD}/lib/*.la

mkdir -p ${OL}/lib
mv ${OLD}/lib/*.so* ${OL}/lib
