#!/bin/sh -e

# Options

PREFIX=${BUILDPREFIX}

OL=${BUILD_ROOT}/cfbuild-openldap${PREFIX}
OLD=${BUILD_ROOT}/cfbuild-openldap-devel${PREFIX}

# Work around bug in libtool: On HP-UX it doesn't understand that there is an
# interdependency from libldap to liblber when installing. Force this knowledge
# on it (for the "make install" below, but must be passed in configure).
LDFLAGS="$LDFLAGS -L${BUILD_ROOT}/cfbuild-openldap-devel$PREFIX/lib"
export LDFLAGS

# Patch

${PATCH} -p1 <host_name_max_hpux.patch
${PATCH} -p0 <no_Sockaddr_redefine.patch

# Configure

./configure --prefix=$PREFIX --enable-shared --disable-slapd --disable-backends \
            --with-tls=openssl --without-gssapi --without-threads \
            CPPFLAGS=-I$PREFIX/include

# Build

gmake -C include
gmake -C libraries

# Test

# Install

gmake -C include install DESTDIR=${BUILD_ROOT}/cfbuild-openldap-devel
gmake -C libraries install DESTDIR=${BUILD_ROOT}/cfbuild-openldap-devel

# Package

rm -rf ${OLD}/etc
rm -f ${OLD}/lib/*.a
rm -f ${OLD}/lib/*.la

mkdir -p ${OL}/lib
mv ${OLD}/lib/*.so* ${OL}/lib
