#!/bin/sh -e

# Options

PREFIX=/var/cfengine

PG=${BUILD_ROOT}/cfbuild-postgresql${PREFIX}
PGD=${BUILD_ROOT}/cfbuild-postgresql-devel${PREFIX}

# Patch

# Configure

# For HP-UX we need to use HP C Compiler to avoid errors related to <net/if.h>
# We need to disable thread safety in order to be able to compile libpq using
# HP C Compiler. Otherwise it'll hang during configure.
# Because of this we also need to modify the link flags to not use the GNU
# specific '-Wl,' indirect flag. It should be passed directly instead.
LDFLAGS="`echo $LDFLAGS | sed -e 's/-Wl,//g'`"
export LDFLAGS
CC=cc ./configure --prefix=$PREFIX --without-zlib --without-readline --disable-thread-safety

# Build

gmake -C src/bin/pg_config
gmake -C src/backend ../../src/include/utils/fmgroids.h
gmake -C src/interfaces/libpq

# Test

# Install

gmake install -C src/bin/pg_config DESTDIR=${BUILD_ROOT}/cfbuild-postgresql-devel
gmake install -C src/include DESTDIR=${BUILD_ROOT}/cfbuild-postgresql-devel
gmake install -C src/interfaces/libpq DESTDIR=${BUILD_ROOT}/cfbuild-postgresql-devel

# Package

rm -f ${PGD}/include/pg_config*.h
rm -rf ${PGD}/include/postgresql/server
rm -f ${PGD}/lib/*.a
rm -rf ${PGD}/share

mkdir -p ${PG}/lib
mv ${PGD}/lib/libpq.so* ${PG}/lib
