#!/bin/sh

# Options

PREFIX=${BUILDPREFIX}

PC=${BUILD_ROOT}/cfbuild-pcre${PREFIX}
PCD=${BUILD_ROOT}/cfbuild-pcre-devel${PREFIX}

# Configure

./configure --prefix=$PREFIX --enable-unicode-properties -disable-cpp

# Build

make

# Test

if [ "$TESTS" != no ]; then
  make check
fi

# Install

make install DESTDIR=${BUILD_ROOT}/cfbuild-pcre-devel
# Package

rm -f ${PCD}/bin/pcregrep
rm -f ${PCD}/bin/pcretest
rm -f ${PCD}/lib/*.a
rm -f ${PCD}/lib/*.la
rm -rf ${PCD}/share

mkdir -p ${PC}/lib
mv ${PCD}/lib/*.so* ${PC}/lib

