#!/bin/sh

# Options

PREFIX=${BUILDPREFIX:-/var/cfengine}

INSTALL_ROOT=${BUILD_ROOT}/cfbuild-pcre

if [ -z "$MAKE" ]
then
    export MAKE=`which make`
fi

# Configure

./configure --prefix=$PREFIX --enable-unicode-properties --disable-cpp --enable-shared

# Build

${MAKE}

# Test

if [ "$TESTS" != no ]; then
  ${MAKE} -s check
fi

# Install

make install DESTDIR=${INSTALL_ROOT}

# Package

# rm -f ${PCD}/bin/pcregrep
# rm -f ${PCD}/bin/pcretest
# rm -f ${PCD}/lib/*.a
# rm -f ${PCD}/lib/*.la
# rm -rf ${PCD}/share

# mkdir -p ${PC}/lib
# mv ${PCD}/lib/*.so* ${PC}/lib

