#!/bin/sh -ex

. `dirname "$0"`/functions

GITSHAOF="core buildscripts buildscripts/deps-packaging"

case "$PROJECT" in
  community)
    NOVA=no
    ;;
  nova)
    NOVA=yes
    GITSHAOF="$GITSHAOF enterprise"
    if test "x$ROLE" = "xhub"
    then
      GITSHAOF="$GITSHAOF nova"
    fi
    ;;
  *)
    echo "Unknown project: $PROJECT"
    exit 42;;
esac

projects="core masterfiles"
if test "x$NOVA" = "xyes"
then
  projects="$projects enterprise"
fi
if test "x$ROLE" = "xhub"
then
  projects="$projects nova"
fi

for p in $projects
do
    (cd $BASEDIR/$p && NO_CONFIGURE=1 ./autogen.sh) || false
done

for i in $GITSHAOF
do
    if [ -d $BASEDIR/$i ] && [ ! -f $BASEDIR/$i/revision ]
    then
        R=$(cd $BASEDIR/$i && git log --pretty='format:%h' -1 -- .) || false
        echo $R | tr -d '\n' > $BASEDIR/$i/revision
    fi
done


detected_versions=`echo $projects  \
    | xargs -n1  \
    | sed "s|.*|$BASEDIR/&/CFVERSION|"  \
    | xargs cat`
number_of_different_versions=`echo $detected_versions  \
    | tr ' ' '\n'  \
    | sed -e 's/\([0-9]*\.[0-9]*\.[0-9]*\).*/\1/'  \
    | uniq  |  wc -l`

if [ "$number_of_different_versions" -ne 1 ]
then
    echo "Detected versions mismatch:" "$detected_versions"  1>&2
    exit 33
fi
