#!/bin/sh

. `dirname "$0"`/functions
. detect-environment
. compile-options

# WARNING we alter the buildslave: we remove UNWANTED_DEPS


### SYSTEM PACKAGE DEPENDENCIES ###
# Libtool is unwanted because "libltdl" polutes our package dependencies.
# The rest are wanted only on the machine doing "autogen.sh",
#     aka buildmaster, which is *different* from the buildslaves
### TODO add to the unwanted list:    bison byacc flex
### TODO unfortunately autoconf is installed by autobuild policy


case "$OS" in
    rhel|centos)
        DEP_LIST="gcc-c++ ncurses ncurses-devel pkgconfig rpm-build pam-devel"
        UNWANTED_DEPS="libtool-ltdl libtool-ltdl-devel"
        ;;
    debian|ubuntu)
        DEP_LIST="dpkg-dev debhelper g++ pkg-config build-essential libpam0g-dev"
        UNWANTED_DEPS="libltdl-dev libltdl7"
        ;;

    # SKIP IN UNKNOWN OS
    *)
        echo "$0: not implemented for OS $OS, skipping"
        exit 0
        ;;
esac

# Fakeroot is here: http://dl.atrpms.net/el5-$1/atrpms/stable/fakeroot-1.6.4-15.1.el5.$1.rpm
#          It is needed by the debian buildslaves for their packaging scripts
case "$OS-$OS_VERSION" in
    rhel-* | centos-* ) DEP_LIST="$DEP_LIST" ;;
    *)                  DEP_LIST="$DEP_LIST fakeroot"    ;;
esac


DEP_LIST="$DEP_LIST rsync gcc make sudo wget"
#UNWANTED_DEPS="$UNWANTED_DEPS libtool"    # TODO automake autoconf bison byacc flex


RET=0
for unwanted in $UNWANTED_DEPS
do
    if query_pkg $unwanted
    then
        echo "ERROR Found unwanted package:" $unwanted
        RET=1
    fi
done

for dep in $DEP_LIST
do
    if query_pkg $dep
    then true
    else
        echo "ERROR Missing system package:" $dep
        RET=1
    fi
done


# Exit with the right exit code
if [  $RET = 0  ]
then
    echo "$0: SUCCESS buildslave is correctly setup"
    exit 0
else
    echo "$0: FAILURE buildslave is NOT correctly setup"
    echo "You should edit the policy in autobuild to fix the issues"
    exit 1
fi
