#!/bin/sh

. `dirname "$0"`/functions
. detect-environment
. compile-options


# WARNING we alter the buildslave: we remove UNWANTED_DEPS


### SYSTEM PACKAGE DEPENDENCIES ###
# Fakeroot is here: http://dl.atrpms.net/el5-$1/atrpms/stable/fakeroot-1.6.4-15.1.el5.$1.rpm
# Libtool is unwanted because "libltdl" polutes our package dependencies.
# The rest are wanted only on the machine doing "autogen.sh",
#which is *different* from the buildslaves
### TODO add to the unwanted list:    bison byacc flex autoconf automake
###      unfortunately they are automatically installed at some later stage...


case "$OS" in
    rhel|centos)
        DEP_LIST="gcc-c++ ncurses ncurses-devel pkgconfig rpm-build pam-devel"
        UNWANTED_DEPS="libtool-ltdl libtool-ltdl-devel"
        ;;
    debian|ubuntu)
        DEP_LIST="dpkg-dev debhelper g++ libncurses5 pkg-config build-essential libpam0g-dev"
        UNWANTED_DEPS="libltdl7 libltdl-dev"
        ;;

    # SKIP IN UNKNOWN OS
    *)
        echo "$0: not implemented for OS $OS, skipping"
        exit 0
        ;;
esac

DEP_LIST="$DEP_LIST ntp rsync gcc make fakeroot "
UNWANTED_DEPS="$UNWANTED_DEPS libtool autoconf automake"


RET=0
for unwanted in $UNWANTED_DEPS
do
    if query_pkg $unwanted
    then
        echo "Removing unwanted package:" $unwanted
        uninstall_pkg $unwanted    ||     echo FAILURE && RET=1
    fi
done

for dep in $DEP_LIST
do
    if query_pkg $dep
    then true
    else
        echo "ERROR Missing system package:" $dep
        RET=1
    fi
done


# Exit with the right exit code
if [  $RET = 0  ]
then
    echo "$0: SUCCESS buildslave is correctly setup"
    exit 0
else
    echo "$0: FAILURE buildslave is NOT correctly setup"
    exit 1
fi
