#!/bin/sh

# This script cleans a build machine by uninstalling cfbuild- prefixed packages
# and by removing the contents of the PREFIX directory.
#
# Don't run this script on your dev machine!
# You may accidentally delete something very important.

. "$(dirname "$0")"/functions
. detect-environment

log_debug "Removing all cfbuild packages..."
run_and_print_on_failure uninstall_cfbuild

if [ -z "$PREFIX" ] || [ "$PREFIX" = "/" ]; then
    fatal "\$PREFIX is not defined, is empty, or is set to the root directory. Aborting to prevent accidental deletion."
fi

log_debug "Cleaning build host by deleting $PREFIX"
case $OS in
aix)
    sudo rm -rf "$PREFIX"/*
    ;;
*)
    sudo rm -rf "$PREFIX"
    ;;
esac
