#!/bin/sh

. `dirname "$0"`/functions
. detect-environment

uninstall_cfbuild

case $OS in
aix)
sudo rm -rf /var/cfengine/*
;;
*)
sudo rm -rf /var/cfengine
;;
esac

$BASEDIR/buildscripts/build-scripts/build-environment-check
