#!/bin/sh -x

. `dirname "$0"`/functions
. detect-environment
. compile-options

case "$TEST_MACHINE" in
    chroot)
        # Don't lose the trailing slash!
        TESTMACHINE_URI=$HOME/testmachine-chroot/
        ;;
    *)
        # Add VMs, etc here.
        echo "Only chroot test machines are supported at the moment."
        exit 1
        ;;
esac

INCLUDES='--include=test.* --include=summary.*'

# Note: Don't use sudo or "rsync -a", because we don't want root-owned files
# to show up in the results.
rsync -rv $INCLUDES --exclude="*" $TESTMACHINE_URI$BASEDIR/core/tests/acceptance/ $BASEDIR/core/tests/acceptance/
rsync -rv $INCLUDES --exclude="*" $TESTMACHINE_URI$BASEDIR/enterprise/tests/acceptance/ $BASEDIR/enterprise/tests/acceptance/
rsync -rv $INCLUDES --exclude="*" $TESTMACHINE_URI$BASEDIR/masterfiles/tests/acceptance/ $BASEDIR/masterfiles/tests/acceptance/
