#!/bin/sh -x

. `dirname "$0"`/functions
. detect-environment
. compile-options

P=/var/cfengine

ARGS="--prefix=$P --with-openssl=$P --with-pcre2=$P --with-lmdb=$P --enable-docs=all"

cd $BASEDIR/core && env $OPTS ./configure $ARGS
