#!/bin/sh -x

. `dirname "$0"`/functions
. detect-environment
. compile-options
. version

WIXPATH="$HOME/wix"

# Wine can handle these tools under the following conditions:
# * You must use Wine 32-bit (wine:i386)
# * The host must have run "winetricks dotnet45" and clicked through all the
#   installations.
#
# This was tested with Wix tools 3.10.
CANDLE="wine $WIXPATH/candle.exe"
LIGHT="wine $WIXPATH/light.exe"

if [ -z $JOB_NAME ]; then
  DIRNAME=build-$VERSION-$ARCH
else
  DIRNAME=$(echo ${JOB_NAME} |sed 's/\(.*\)\/.*/\1/g')
fi

PKGD=$BASEDIR/packaging/cfengine-nova/pkg
P=$PKGD/$DIRNAME

pre()
{
  rm -rf $PKGD
  mkdir -p $P/bin

  cp -a $BUILDPREFIX/bin/* $P/bin
  cp -a $BASEDIR/cfengine/dist$BUILDPREFIX/bin/* $P/bin

  case "$ARCH" in
    x86) cp -a $BASEDIR/enterprise/libcfenterprise/cf.events.i686.dll $P/bin/cf.events.dll;;
    x64) cp -a $BASEDIR/enterprise/libcfenterprise/cf.events.x86_64.dll $P/bin/cf.events.dll;;
    *)
      echo "Unknown architecture: $ARCH"
      exit 1;;
  esac

  cp $BASEDIR/buildscripts/packaging/cfengine-nova/cfengine-nova.wxs $P
}

candle()
{
  REVISION="$1"
  $CANDLE -dCfSourceDir=. -dCfVersion=$REVISION -dCfArch=$ARCH cfengine-nova.wxs
}

light()
{
  $LIGHT -sval -sice:ICE20 -ext WixUtilExtension cfengine-nova.wixobj
}

package()
{
  cd $P

  if [ -z $EXPLICIT_VERSION ]
  then
    case $BUILD_TYPE in
      RELEASE)
        REVISION=$VERSION.0
        ;;
      DEBUG|CODE_COVERAGE)
        MAIN_VERSION=${VERSION%\~*}
        REVISION=$MAIN_VERSION.$BUILD_NUMBER
        ;;
    esac
  else
    REVISION=$EXPLICIT_VERSION.65534
    #fix me, come up with some way of specifying a version number. right now get rid of alphabets.
    REVISION=$(echo $REVISION | sed 's/[a-z]*//g');
  fi

  # convert any alphabets in revison to int as no alphabets are allowed in windows package version
  alphabet=$(echo $REVISION|sed -e 's/[^a-zA-Z]*\([a-zA-Z]*\).*/\1/');
  convert=$(printf '%d' "'$alphabet")
  REVISION=$(echo $REVISION|sed -e "s/$alphabet/$convert/");

  candle "$REVISION"
  light
}

post()
{
  mkdir -p $BASEDIR/cfengine-nova
  mv $P/cfengine-nova.msi $BASEDIR/cfengine-nova
  cd $BASEDIR/cfengine-nova

  # For some reason candle is giving file no permissions at all.
  chmod 644 cfengine-nova.msi

  case $BUILD_TYPE in
    RELEASE)
      PKGNAME="cfengine-nova-$VERSION"
      ;;
    DEBUG|CODE_COVERAGE)
      PKGNAME="cfengine-nova-$VERSION-$BUILD_NUMBER"
      ;;
  esac

  case $ARCH in
    x86)
      mv cfengine-nova.msi $PKGNAME-i686.msi
      ;;
    x64)
      mv cfengine-nova.msi $PKGNAME-x86_64.msi
      ;;
  esac
}

pre
package
post
