#!/bin/sh -x

. `dirname "$0"`/functions
. detect-environment
. compile-options
. version

# Select what to build

case "$PROJECT-$ROLE" in
  community-*)
    PKG=cfengine-community
    DEB_BUILD_OPTIONS=
    RPMBUILD_OPTIONS=;;
  nova-hub)
    PKG=cfengine-nova-hub
    DEB_BUILD_OPTIONS=
    RPMBUILD_OPTIONS="--define 'with_expansion 1'"
    ;;
  nova-agent)
    PKG=cfengine-nova
    DEB_BUILD_OPTIONS=
    RPMBUILD_OPTIONS=;;
  *)
    echo "Unknown packaging type: $PROJECT-$ROLE"
    exit 42;;
esac

case "$BUILD_TYPE" in
  DEBUG)
    DEB_BUILD_OPTIONS="$DEB_BUILD_OPTIONS noopt nostrip"
    RPMBUILD_OPTIONS="$RPMBUILD_OPTIONS --define 'with_optimize 0'"
    RPMBUILD_OPTIONS="$RPMBUILD_OPTIONS --define 'with_debugsym 1'"
    ;;
  RELEASE|CODE_COVERAGE)
     DEB_BUILD_OPTIONS="nostrip"
    ;;
  *)
    echo "Unknown build type: $BUILD_TYPE"
    exit 42;;
esac

# Clean -devel packages, so their contents doesn't end up in our packages, set env variable for dev trouble shooting
if [ "x$LEAVE_DEVEL_PACKAGES" != "xyes" ]
then
uninstall_cfbuild_devel
fi
# Build it

P="$BASEDIR/buildscripts/packaging/$PKG"

case "$VERSION" in
  *~*)
    # everything before the tilde
    MAIN_VERSION=${VERSION%\~*}
    # everything after the tilde
    SUPP_VERSION=${VERSION#*~};;
  *)
    MAIN_VERSION=${VERSION}
    SUPP_VERSION=;;
esac

case "$PACKAGING" in
  rpm|lpp)
    mkdir -p $BASEDIR/$PKG/BUILD
    mkdir -p $BASEDIR/$PKG/RPMS
    mkdir -p $BASEDIR/$PKG/SOURCES
    mkdir -p $BASEDIR/$PKG/SRPMS

    SPEC=$P/$PKG.spec
    PREINSTALL=$P/generated.preinstall
    POSTINSTALL=$P/generated.postinstall
    PREREMOVE=$P/generated.preremove
    POSTREMOVE=$P/generated.postremove

    if [ "$PACKAGING" = lpp ]
    then
        SPECIN=$P/$PKG.spec.aix.in
    else
        SPECIN=$P/$PKG.spec.in
    fi

    $P/../common/produce-script $PKG preinstall rpm > $PREINSTALL
    $P/../common/produce-script $PKG postinstall rpm > $POSTINSTALL
    $P/../common/produce-script $PKG preremove rpm > $PREREMOVE
    $P/../common/produce-script $PKG postremove rpm > $POSTREMOVE


    RPM_VERSION=$MAIN_VERSION

    # Set RPM_RELEASE, which sets the "release" tag in the RPM spec
    # file, which is an incremental version of the specific package in
    # case it is rebuilt and re-released for any reason.

    if [ -z "$SUPP_VERSION" ]
    then

        if [ $BUILD_TYPE = "RELEASE" ]
        then
            RPM_RELEASE=${EXPLICIT_RELEASE:-1}
        else
            RPM_RELEASE=$BUILD_NUMBER
        fi

    else
        # SUPP_VERSION is the part of the git tag after the dash, e.g. build1

        if [ $BUILD_TYPE = "RELEASE" ]
        then
            RPM_RELEASE=$SUPP_VERSION
        else
            RPM_RELEASE=$SUPP_VERSION.$BUILD_NUMBER
        fi
    fi

    sed \
        -e "s/@@VERSION@@/$RPM_VERSION/g" \
        -e "s/@@RELEASE@@/$RPM_RELEASE/g" \
        -e "/^%pre\$/r $PREINSTALL" \
        -e "/^%post\$/r $POSTINSTALL" \
        -e "/^%preun\$/r $PREREMOVE" \
        -e "/^%postun\$/r $POSTREMOVE" \
        $SPECIN > $SPEC

    for i in `find $BASEDIR/buildscripts/packaging/$PKG ! -name "*.spec"`
    do
        (cd $BASEDIR/$PKG/SOURCES; ln -sf $i) || false
    done

    # eval and double quoting is needed to separate args,
    # example cmd --define 'a b':
    #     - argv[1] = --define
    #     - argv[2] = a b
    eval $RPMBUILD_CMD -bb \
      --define "'_topdir $BASEDIR/$PKG'" \
      --define "'buildprefix $BUILDPREFIX'" \
      --define "'_basedir $BASEDIR'" \
      $RPMBUILD_OPTIONS $SPEC


    if [ "$PACKAGING" = lpp ]
    then
        # Create AIX bff packages
        chmod +x $P/$PKG.bff.sh
        $P/$PKG.bff.sh $RPM_VERSION $BASEDIR
    fi
    ;;

  deb)
    if [ "$BUILDPREFIX" = "/opt/cfengine" ]
    then
       #change the base path of cfengine files
        for i in $P/debian/$PKG*;  do
          sed -i "s/var/opt/g" $i
        done 
    fi

    rm -rf $BASEDIR/$PKG/pkg
    mkdir -p $BASEDIR/$PKG/pkg
    cp -a $P/* $BASEDIR/$PKG/pkg

    if [ $BUILD_TYPE = "RELEASE" ]
    then

      if [ -z $EXPLICIT_RELEASE ]
      then
          DEB_VERSION=$VERSION-1
        else
          DEB_VERSION=$VERSION-$EXPLICIT_RELEASE
        fi

   else
      DEB_VERSION=$VERSION~$BUILD_NUMBER
    fi


    sed -e "s/@@VERSION@@/$DEB_VERSION/" $BASEDIR/$PKG/pkg/debian/changelog.in > $BASEDIR/$PKG/pkg/debian/changelog

    $P/../common/produce-script $PKG preinstall deb > $BASEDIR/$PKG/pkg/debian/$PKG.preinst
    $P/../common/produce-script $PKG postinstall deb > $BASEDIR/$PKG/pkg/debian/$PKG.postinst
    $P/../common/produce-script $PKG preremove deb > $BASEDIR/$PKG/pkg/debian/$PKG.prerm
    $P/../common/produce-script $PKG postremove deb > $BASEDIR/$PKG/pkg/debian/$PKG.postrm

    (cd $BASEDIR/$PKG/pkg; export DEB_BUILD_OPTIONS="$DEB_BUILD_OPTIONS"; dpkg-buildpackage -b -us -uc -rfakeroot) || false
    ;;

  solaris)
    PREFIX=/var/cfengine
    sudo rm -rf $BASEDIR/$PKG/pkg
    mkdir -p $BASEDIR/$PKG/pkg

    rsync -lpr $BASEDIR/cfengine/dist/* $BASEDIR/$PKG/pkg/
    rsync -lpr /var/cfengine/bin/* $BASEDIR/$PKG/pkg/var/cfengine/bin/
    rsync -lpr /var/cfengine/lib/* $BASEDIR/$PKG/pkg/var/cfengine/lib/

    cd $BASEDIR/$PKG/pkg
    # IMPORTANT: Before this step, do not copy any files into the current
    # directory that shouldn't be in the package, otherwise they will be
    # included as package files.
    pkgproto .=/ > ../prototype.tmp
    mv ../prototype.tmp .

    # Paste several things together in the prototype.
    (
      cat $P/solaris/prototype.head
      # Replace last two words with "root root" and filter out directories that
      # aren't ours.
      sed -e 's/^\([fd].* \)[^ ][^ ]*  *[^ ][^ ]*$/\1root root/' prototype.tmp | egrep '^([^d]|d none /var/cfengine)'
    ) > prototype

    ARCH=`uname -p`
    sed -e "s/@@PKG@@/$PKG/g;s/@@ARCH@@/$ARCH/g;s/@@VERSION@@/$VERSION/g" $P/solaris/pkginfo.in > $BASEDIR/$PKG/pkg/pkginfo

    $P/../common/produce-script $PKG preinstall pkg > preinstall
    $P/../common/produce-script $PKG postinstall pkg > postinstall
    $P/../common/produce-script $PKG preremove pkg > preremove
    $P/../common/produce-script $PKG postremove pkg > postremove

    pkgmk -o -r `pwd` -d $BASEDIR/$PKG/pkg
    NAME=CFE$PKG-$VERSION-$ARCH.pkg
    pkgtrans -o -s $BASEDIR/$PKG/pkg $BASEDIR/$PKG/$NAME CFE$PKG
    ;;
  freebsd)
	  PREFIX=/var/cfengine
	  rm -rf $BASEDIR/$PKG/pkg
	  mkdir -p $BASEDIR/$PKG/pkg${PREFIX}

	  cp -pr $P/freebsd/* $BASEDIR/$PKG/pkg/
	  cp -pr $BASEDIR/cfengine/dist/var/cfengine/* $BASEDIR/$PKG/pkg${PREFIX}
	  cp -pr /var/cfengine/bin/* $BASEDIR/$PKG/pkg${PREFIX}/bin
	  cp -pr /var/cfengine/lib/* $BASEDIR/$PKG/pkg${PREFIX}/lib

	  cd $BASEDIR/$PKG/pkg
	  echo "@comment pkg-plist,v 1.00 `date`" >> pkg-plist
	  echo "@comment ORIGIN:sysutils/cfengine-nova" >> pkg-plist
      pkgdir=$BASEDIR/$PKG/pkg/
      for f in `find $BASEDIR/$PKG/pkg/ | egrep -v 'pkg-comment|pkg-descr|pkg-plist.foot|pkg-plist'`; do

      		  destf=${f#$pkgdir}
              if [ -f $destf ]; then
                      echo "$destf" >> pkg-plist
              fi
       done

       cat pkg-plist.foot >> pkg-plist

       /usr/sbin/pkg_create -j -f ${pkgdir}/pkg-plist -c ${pkgdir}/pkg-comment -d ${pkgdir}/pkg-descr -p ${pkgdir} ${pkgdir}/cfengine-nova-$VERSION\_1.tbz

       cd $pkgdir/

       tar xvf cfengine-nova-$VERSION\_1.tbz

       head -n 2 ./+CONTENTS > plist-head
       sed '1,3d' ./+CONTENTS > tmp
       rm ./+CONTENTS
       cat plist-head > CONTENTS
       echo "@cwd /" >> CONTENTS
       cat tmp >> CONTENTS
       rm plist-head tmp
       mv CONTENTS ./+CONTENTS
       tar cjvf cfengine-nova-$VERSION\_1.tbz +CONTENTS +DESC +COMMENT var/
	  ;;
  hpux)
      PREFIX=/var/cfengine
      ARCH=`uname -m`
      OS_VER=`uname -r`

      rm -rf $BASEDIR/$PKG/pkg
      mkdir -p $BASEDIR/$PKG/pkg${PREFIX}

      cp -pr $BASEDIR/cfengine/dist/* $BASEDIR/$PKG/pkg
      cp -pr /var/cfengine/lib/* $BASEDIR/$PKG/pkg${PREFIX}/lib

      PREINSTALL=$BASEDIR/$PKG/pkg/generated.preinstall
      POSTINSTALL=$BASEDIR/$PKG/pkg/generated.postinstall
      PREREMOVE=$BASEDIR/$PKG/pkg/generated.preremove
      POSTREMOVE=$BASEDIR/$PKG/pkg/generated.postremove

      $P/../common/produce-script $PKG preinstall depot > $PREINSTALL
      $P/../common/produce-script $PKG postinstall depot > $POSTINSTALL
      $P/../common/produce-script $PKG preremove depot > $PREREMOVE
      $P/../common/produce-script $PKG postremove depot > $POSTREMOVE

      cd $BASEDIR/$PKG/pkg/

      $P/hpux/psf.pl . $PKG $VERSION > $BASEDIR/$PKG/$PKG-$VERSION.psf
      /usr/sbin/swpackage -s $BASEDIR/$PKG/$PKG-$VERSION.psf -x media_type=tape @ $BASEDIR/$PKG/pkg/$PKG-$VERSION-$OS_VER-$ARCH.depot
      ;;
  msi)
    package-msi;;
  *)
    echo "Unknown packaging system: $PACKAGING"
    exit 1;;
esac
