#!/bin/sh

. `dirname "$0"`/functions
. detect-environment
. compile-options
. version

# Select what to build

case "$PROJECT-$WEB" in
  community-*)
    PKG=cfengine-community
    DEB_BUILD_OPTIONS=
    RPMBUILD_OPTIONS=;;
  nova-yes)
    PKG=cfengine-nova
    DEB_BUILD_OPTIONS=expansion
    RPMBUILD_OPTIONS=--define="with_expansion 1";;
  nova-no)
    PKG=cfengine-nova
    DEB_BUILD_OPTIONS=
    RPMBUILD_OPTIONS=;;
  *)
    echo "Unknown packaging type: $PROJECT-$WEB"
    exit 42;;
esac

case "$BUILD_TYPE" in
  debug)
    DEB_BUILD_OPTIONS="$DEB_BUILD_OPTIONS noopt nostrip"
    RPMBUILD_OPTIONS="$RPMBUILD_OPTIONS "--define="with_optimize 0"
    RPMBUILD_OPTIONS="$RPMBUILD_OPTIONS "--define="with_debugsym 1";;
  quick|full|release)
    ;;
  *)
    echo "Unknown build type: $BUILD_TYPE"
    exit 42;;
esac

# Clean -devel packages, so their contents doesn't end up in our packages

uninstall_cfbuild_devel

# Build it

P="$BASEDIR/autobuild/packaging/$PKG"

case "$VERSION" in
  *~*)
    MAIN_VERSION=${VERSION%\~*}
    SUPP_VERSION=${VERSION#*~};;
  *)
    MAIN_VERSION=${VERSION}
    SUPP_VERSION=;;
esac

case "$PACKAGING" in
  rpm)
    mkdir -p $BASEDIR/$PKG/BUILD
    mkdir -p $BASEDIR/$PKG/RPMS
    mkdir -p $BASEDIR/$PKG/SOURCES
    mkdir -p $BASEDIR/$PKG/SRPMS

    SPEC=$P/$PKG.spec

    if [ -z "$SUPP_VERSION" ]; then
      RPM_VERSION=$MAIN_VERSION

      if [ $BUILD_TYPE = release ]; then
        RPM_RELEASE=1
      else
        RPM_RELEASE=0.$BUILD_NUMBER
      fi
    else
      RPM_VERSION=$MAIN_VERSION

      if [ $BUILD_TYPE = release ]; then
        RPM_RELEASE=0.$SUPP_VERSION.1
      else
        RPM_RELEASE=0.$SUPP_VERSION.0.$BUILD_NUMBER
      fi
    fi

    sed \
      -e "s/@@VERSION@@/$RPM_VERSION/g" \
      -e "s/@@RELEASE@@/$RPM_RELEASE/g" \
      $SPEC.in > $SPEC

    for i in `find $BASEDIR/autobuild/packaging/$PKG ! -name "*.spec"`; do
      (cd $BASEDIR/$PKG/SOURCES; ln -sf $i) || false
    done

    rpmbuild -bb --define="_topdir $BASEDIR/$PKG" --define="_basedir $BASEDIR" ${RPMBUILD_OPTIONS:+"${RPMBUILD_OPTIONS}"} $SPEC
    ;;
  deb)
    rm -rf $BASEDIR/$PKG/pkg
    mkdir -p $BASEDIR/$PKG/pkg
    cp -a $P/* $BASEDIR/$PKG/pkg

    if [ $BUILD_TYPE = release ]; then
      DEB_VERSION=$VERSION
    else
      DEB_VERSION=$VERSION~$BUILD_NUMBER
    fi

    sed -e "s/@@VERSION@@/$VERSION/" $BASEDIR/$PKG/pkg/debian/changelog.in > $BASEDIR/$PKG/pkg/debian/changelog

    (cd $BASEDIR/$PKG/pkg; DEB_BUILD_OPTIONS="$DEB_BUILD_OPTIONS" dpkg-buildpackage -b -us -uc -rfakeroot) || false
    ;;

  solaris)
    rm -rf $BASEDIR/$PKG/pkg
    mkdir -p $BASEDIR/$PKG/pkg

#    cp -pr $P/solaris/etc/ $BASEDIR/$PKG/pkg/
#    cp -pr $P/solaris/postinstall $BASEDIR/$PKG/pkg/
#    cp -pr $P/solaris/preremove $BASEDIR/$PKG/pkg/
    cp -pr $P/solaris/* $BASEDIR/$PKG/pkg/
    cp -pr $BASEDIR/core/dist/var/cfengine/* $BASEDIR/$PKG/pkg
    cp -pr /var/cfengine/bin/* $BASEDIR/$PKG/pkg/bin
    cp -pr /var/cfengine/lib/* $BASEDIR/$PKG/pkg/lib
    
    ARCH=`uname -p`
    sed -e "s/@@PKG@@/$PKG/g;s/@@ARCH@@/$ARCH/g;s/@@VERSION@@/$VERSION/g" $BASEDIR/$PKG/pkg/pkginfo.in > $BASEDIR/$PKG/pkg/pkginfo
    
    cd $BASEDIR/$PKG/pkg
    cat prototype.head > prototype.tmp && find . | egrep -v 'postinstall|pkginfo|prototype|preremove|./etc|prototype.head|pkginfo.in' | pkgproto >> prototype.tmp

    sed -e "s/build/root/g;s/sudoers/root/g" prototype.tmp > prototype
#    pkgmk -o -r `pwd`
    pkgmk -o -r `pwd` -d $BASEDIR/$PKG/pkg
#    cd /var/spool/pkg/
    NAME=CFE$PKG-$VERSION-$ARCH.pkg
#    echo "$NAME"
    pkgtrans -o -s $BASEDIR/$PKG/pkg $BASEDIR/$PKG/$NAME CFE$PKG
    ;;
  msi)
    package-msi;;
  *)
    echo "Unknown packaging system: $PACKAGING"
    exit 1;;
esac
