#!/bin/sh

. "$(dirname "$0")"/functions
. detect-environment
. compile-options

if [ "$BUILD_TYPE" != "RELEASE" ]; then
    echo "Debug symbols not requested"
    exit 0
else
    echo "Producing debug symbols"
fi

EXECUTABLES_DIR="$BASEDIR/cfengine/dist$PREFIX/bin"
EXECUTABLES_LIST=$(ls "$EXECUTABLES_DIR"/cf-*)
LIBRARIES_DIR="$BASEDIR/cfengine/dist$PREFIX/lib"
LIBRARIES_LIST=$(ls "$LIBRARIES_DIR"/*.so*)
DEBUG_SUFFIX=debug
PAYLOAD_DIR=payload
EXECUTABLES_PAYLOAD_DIR=$PAYLOAD_DIR/exe
LIBRARIES_PAYLOAD_DIR=$PAYLOAD_DIR/lib

# Print build information
echo "EXECUTABLES_DIR  = $EXECUTABLES_DIR"
echo "EXECUTABLES_LIST = $EXECUTABLES_LIST"
echo "LIBRARIES_DIR    = $LIBRARIES_DIR"
echo "LIBRARIES_LIST   = $LIBRARIES_LIST"
echo "DEBUG_SUFFIX     = $DEBUG_SUFFIX"
echo "PAYLOAD_DIR      = $PAYLOAD_DIR"

# Make a temporary folder to store the debug symbols once they are produced
mkdir $PAYLOAD_DIR
mkdir $EXECUTABLES_PAYLOAD_DIR
mkdir $LIBRARIES_PAYLOAD_DIR

# We put the debug symbols on the same folder as the executables.
# This way debugging gets a little bit simpler.

for i in $EXECUTABLES_LIST; do
    echo "Taking debug symbols from: $i and putting it into: $i.$DEBUG_SUFFIX"
    objcopy --only-keep-debug "$i" "$i.$DEBUG_SUFFIX"
    strip --strip-debug --strip-unneeded "$i"
    objcopy --add-gnu-debuglink="$i.$DEBUG_SUFFIX" "$i"
    chmod -x "$i.$DEBUG_SUFFIX"
    gzip "$i.$DEBUG_SUFFIX"
    mv "$i.$DEBUG_SUFFIX.gz" $EXECUTABLES_PAYLOAD_DIR
done

# We put the debug symbols for libraries on the same folder as the libraries.

for i in $LIBRARIES_LIST; do
    echo "Taking debug symbols from: $i and putting it into: $i.$DEBUG_SUFFIX"
    objcopy --only-keep-debug "$i" "$i.$DEBUG_SUFFIX"
    strip --strip-debug --strip-unneeded "$i"
    objcopy --add-gnu-debuglink="$i.$DEBUG_SUFFIX" "$i"
    chmod -x "$i.$DEBUG_SUFFIX"
    gzip "$i.$DEBUG_SUFFIX"
    mv "$i.$DEBUG_SUFFIX.gz" $LIBRARIES_PAYLOAD_DIR
done

# Write the installation script
log_debug "Writing the installation script"
cat <<EOF >> $PAYLOAD_DIR/install-ds.sh
#!/bin/sh
# Install debug symbols for executables
for i in \`ls exe/*.gz\`; do
  gunzip \$i
done
mv exe/*.$DEBUG_SUFFIX $PREFIX/bin
# Install debug symbols for libraries
for i in \`ls lib/*.gz\`; do
  gunzip \$i
done
mv lib/*.$DEBUG_SUFFIX $PREFIX/lib
exit 0
EOF

# Write the decompression script
log_debug "Writing the decompression script"
cat <<EOF >> decompress-ds.sh
#!/bin/sh
echo "Installing debug symbols"
TMPDIR=\`mktemp -d /tmp/ds.XXXXXX\`; export TMPDIR
ARCHIVE=\`awk '/^__ARCHIVE_BELOW__/ {print NR + 1; exit 0; }' \$0\`
tail -n+\$ARCHIVE \$0 | tar xzv -C \$TMPDIR
echo "Installer ready - starting installation"
CDIR=\`pwd\`
cd \$TMPDIR/$PAYLOAD_DIR
chmod 755 install-ds.sh
chmod 755 uninstall-ds.sh
./install-ds.sh
cd \$CDIR
#echo "rm -rf \$TMPDIR"  >> decompress-ds.sh
exit 0
__ARCHIVE_BELOW__
EOF

# Write the uninstall script
log_debug "Writing the uninstall script"
cat <<EOF >> $PAYLOAD_DIR/uninstall-ds.sh
#!/bin/sh
echo "Uninstalling debug symbols"
rm -f "$PREFIX"/bin/*.\$DEBUG_SUFFIX
rm -f "$PREFIX"/lib/*.\$DEBUG_SUFFIX
echo "Done"
EOF

# Now create the self extracting script
echo "Creating the self extracting script"
tar cf payload.tar $PAYLOAD_DIR
if [ -e "payload.tar" ]; then
    gzip payload.tar
    if [ -e "payload.tar.gz" ]; then
        cat decompress-ds.sh payload.tar.gz >cfengine-ds-"$OS"-"$OS_VERSION"-"$ARCH".bsx
    else
        echo "File not found"
        exit 1
    fi
    echo "cfengine-ds-$OS-$OS_VERSION-$ARCH.bsx created"
fi
# Put the script in a sensible place
mkdir -p output/debug_symbols
mv -- *.bsx output/debug_symbols

# Clean up after ourserlves
rm -f decompress-ds.sh
rm -f install-ds.sh
rm -f uninstall-ds.sh
rm -rf $PAYLOAD_DIR

echo "Debug symbols produced."

exit 0
