#!/bin/sh

. "$(dirname "$0")"/functions
. detect-environment
. compile-options

# Ensure hostname -f is working (required for some tests)
# This check is limited to Linux only, since on exotics `hostname -f` sometimes
# sets hostname to "-f", and tests mentioned above are not running there anyway.
if [ "$(uname -s)" = "Linux" ]; then
    if ! hostname -f >/dev/null; then
        log_debug "Adding '127.0.0.1 $(hostname).example.com $(hostname)' to '/etc/hosts' to ensure 'hostname -f' is working..."
        echo "127.0.0.1 $(hostname).example.com $(hostname)" >>/etc/hosts
    fi
fi

# We should already be root inside the chroot, so sudo is not necessary,
# and "GAINROOT=env" might be faster.
log_debug "Executing tests on this machine..."
env GAINROOT=env UNSAFE_TESTS=1 "$BASEDIR"/buildscripts/build-scripts/test-on-thismachine
