#!/bin/sh

. "$(dirname "$0")"/functions
. detect-environment
. compile-options
. version
. transfer-to-windowsmachine

#TESTDIR="\"c:\\Users\\jenkins\\tests\\acceptance\""

execute_test() {
    $SSH "$1" cmd /c "cd $TESTDIR\\acceptance && sh -c \"export PATH=/usr/bin:\$PATH;./testall --bindir=/c/Users/jenkins/$DIRNAME/bin/\"" || true
}

get_testresult() {
    cd "$BASEDIR"/core/tests

    echo "cd $TESTDIR/acceptance
get test.log" | $SFTP "$1"

    echo "cd $TESTDIR/acceptance
get test.xml" | $SFTP "$1"
}

# Create $PREFIX/bin directory and by necessary files into it and compresses it into a .zip file
prepare_bin

# Puts the test into a .zip file
prepare_tests

# Copies the .zip files into the test machine
put "$WIX_MACHINE"

# Executes the tests on the test machine
execute_test "$WIX_MACHINE"

# Transfers the test results to this machine
try_run get_testresult "$WIX_MACHINE"
