#!/bin/sh -x

. `dirname "$0"`/functions
. detect-environment
. compile-options

case "$TEST_MACHINE" in
    chroot)
        # Don't lose the trailing slash!
        TESTMACHINE_URI=$HOME/testmachine-chroot/
        EXCLUDES="--exclude testmachine-chroot --exclude .git"
        ;;
    *)
        # Add VMs, etc here.
        echo "Only chroot test machines are supported at the moment."
        exit 1
        ;;
esac

# Filter out "./" parts in the BASEDIR name.
# It confuses the rsync -R mechanism.
# Explanation of sed script:
# * first we replace "/./" with "/" anywhere in the BASEDIR
# * then we remove "/." at the end of the BASEDIR
# This way we avoid errorneously replacing "/." in the
# middle of BASEDIR like "/home/jenkins/.jenkinsdir/etc"
# (Google Cloud Jenkins plugin likes to create them)
BASEDIR_NO_DOT="$(echo $BASEDIR | sed -e 's,/\./,/,g;s,/\.$,,')"
sudo rsync -avR $EXCLUDES --delete --delete-excluded $BASEDIR_NO_DOT/ $TESTMACHINE_URI  >rsync.log
sudo rsync -avR $EXCLUDES --delete --delete-excluded /var/cfengine/ $TESTMACHINE_URI    >>rsync.log
