#!/bin/sh -x

. "$(dirname "$0")"/functions
. detect-environment
. compile-options

case "$TEST_MACHINE" in
chroot)
    # Don't lose the trailing slash!
    TESTMACHINE_URI=$HOME/testmachine-chroot/
    EXCLUDES="--exclude testmachine-chroot --exclude .git"
    ;;
*)
    # Add VMs, etc here.
    echo "Only chroot test machines are supported at the moment."
    exit 1
    ;;
esac

# Filter out "./" parts in the BASEDIR name.
# It confuses the rsync -R mechanism.
# Explanation of sed script:
# * first we replace "/./" with "/" anywhere in the BASEDIR
# * then we remove "/." at the end of the BASEDIR
# This way we avoid errorneously replacing "/." in the
# middle of BASEDIR like "/home/jenkins/.jenkinsdir/etc"
# (Google Cloud Jenkins plugin likes to create them)
BASEDIR_NO_DOT="$(echo "$BASEDIR" | sed -e 's,/\./,/,g;s,/\.$,,')"
touch .keepalive-echo
(while test -e .keepalive-echo; do
    sleep 60
    echo Keep alive
done) &

# shellcheck disable=SC2086
# > Double quote to prevent globbing and word splitting.
# We want word splitting here

# shellcheck disable=SC2024
# > sudo doesn't affect redirects. Use ..| sudo tee file
# We don't care
sudo rsync -avR $EXCLUDES --delete --delete-excluded "$BASEDIR_NO_DOT/" $TESTMACHINE_URI >/tmp/rsync.log
# shellcheck disable=SC2086
# shellcheck disable=SC2024
sudo rsync -avR $EXCLUDES --delete --delete-excluded "$PREFIX/" $TESTMACHINE_URI >>/tmp/rsync.log
rm .keepalive-echo
