#!/bin/sh -x

. "$(dirname "$0")"/functions
. detect-environment
. compile-options

for file in "$BASEDIR"/output/tarballs/cfengine-3.*.tar.gz; do
    SOURCE_TARBALL="$file"
done
if [ -z "$SOURCE_TARBALL" ]; then
    fatal "No matching CFEngine tarball found"
fi

for file in "$BASEDIR"/output/tarballs/cfengine-masterfiles*.tar.gz; do
    case "$file" in
    *pkg.tar.gz)
        # Don't match file ending with pkg.tar.gz
        ;;
    *)
        # This is the file we want
        MASTERFILES_TARBALL="$file"
        break
        ;;
    esac
done
if [ -z "$MASTERFILES_TARBALL" ]; then
    fatal "No matching masterfiles tarball found"
fi

# DELETE the git-checked-out directories, they are tainted with
# ./configure artifacts anyway.  The tarballs are unpacked and symlinked
# into place. That way unpacking of tarballs on all platforms is
# verified.

echo "Ensuring that core and masterfiles are not here"
sudo rm -rf "$BASEDIR/core" "$BASEDIR/masterfiles"
if [ -e "$BASEDIR/core/" ] || [ -e "$BASEDIR/masterfiles/" ]; then
    echo 'core or masterfiles not deleted!'
    echo "core:"
    find "$BASEDIR/core/"
    echo "masterfiles:"
    find "$BASEDIR/masterfiles/"
    exit 1
fi

if [ "$PROJECT" = community ]; then
    sudo rm -rf "$BASEDIR/enterprise" "$BASEDIR/nova" "$BASEDIR/mission-portal"
fi

# NATIVE TAR is being used on purpose, and *not* GNU TAR.

echo "UNPACKING SOURCE TARBALL AND SYMLINKING core"
cd "$BASEDIR"
gzip -dc "$SOURCE_TARBALL" | tar -xf -
ln -s cfengine-3* core

echo "UNPACKING MASTERFILES TARBALL AND SYMLINKING masterfiles/"
gzip -dc "$MASTERFILES_TARBALL" | tar -xf -
ln -s cfengine-masterfiles-* masterfiles
