#!/bin/sh -x

. $(dirname "$0")/functions
. detect-environment
. compile-options

SOURCE_TARBALL="$BASEDIR/output/tarballs/cfengine-3.*.tar.gz"
MASTERFILES_TARBALL=$(ls $BASEDIR/output/tarballs/cfengine-masterfiles*.tar.gz | grep -v 'pkg.tar.gz$')

# DELETE the git-checked-out directories, they are tainted with
# ./configure artifacts anyway.  The tarballs are unpacked and symlinked
# into place. That way unpacking of tarballs on all platforms is
# verified.

echo "Ensuring that core and masterfiles are not here"
sudo rm -rf "$BASEDIR/core" "$BASEDIR/masterfiles"
if [ -e "$BASEDIR/core/" ] || [ -e "$BASEDIR/masterfiles/" ]; then
    echo 'core or masterfiles not deleted!'
    echo "core:"
    find "$BASEDIR/core/"
    echo "masterfiles:"
    find "$BASEDIR/masterfiles/"
    exit 1
fi

if [ x$PROJECT = xcommunity ]; then
    sudo rm -rf "$BASEDIR/enterprise" "$BASEDIR/nova" "$BASEDIR/mission-portal"
fi

# NATIVE TAR is being used on purpose, and *not* GNU TAR.

echo "UNPACKING SOURCE TARBALL AND SYMLINKING core"
cd $BASEDIR
gzip -dc $SOURCE_TARBALL | tar -xf -
ln -s cfengine-3* core

echo "UNPACKING MASTERFILES TARBALL AND SYMLINKING masterfiles/"
gzip -dc $MASTERFILES_TARBALL | tar -xf -
ln -s cfengine-masterfiles-* masterfiles
