#!/usr/xpg4/bin/sh -e

# Options

PREFIX=/var/cfengine

LX=${BUILD_ROOT}/cfbuild-libxml2${PREFIX}
LXD=${BUILD_ROOT}/cfbuild-libxml2-devel${PREFIX}

# Patch

$PATCH -p0 < solaris-8-inttypes.patch
$PATCH -p0 < solaris-huge-val.patch

# Configure

./configure --prefix=${PREFIX} --without-python --without-lzma --without-zlib

# Build

$MAKE

# Test

# Install

$MAKE install DESTDIR=${BUILD_ROOT}/cfbuild-libxml2-devel

# Package

rm -f ${LXD}/bin/xmlcatalog
rm -f ${LXD}/bin/xmllint
rm -f ${LXD}/lib/libxml2.a
rm -f ${LXD}/lib/libxml2.la
rm -f ${LXD}/lib/xml2Conf.sh
rm -rf ${LXD}/share

mkdir -p ${LX}/lib
mv ${LXD}/lib/*.so* ${LX}/lib

