#!/bin/sh

# Options

PREFIX=${BUILDPREFIX}

LX=${BUILD_ROOT}/cfbuild-libxml2${PREFIX}
LXD=${BUILD_ROOT}/cfbuild-libxml2-devel

# Configure

./configure --prefix=$PREFIX --without-python

# Build

gmake


# Install

gmake install DESTDIR=${LXD}
# Package

rm -f ${LXD}/bin/xmlcatalog
rm -f ${LXD}/bin/xmllint
rm -f ${LXD}/lib/libxml2.a
rm -f ${LXD}/lib/libxml2.la
rm -f ${LXD}/lib/xml2Conf.sh
rm -rf ${LXD}/share

mkdir -p ${LX}/bin ${LX}/lib
mv ${LXD}/lib/*.so* ${LX}/lib
