#!/bin/sh

# Options

PREFIX=${BUILDPREFIX:-/var/cfengine}

INSTALL_ROOT=${BUILD_ROOT}/cfbuild-libxml2

LDFLAGS="${LDFLAGS} -fPIC"

if [ -z "${MAKE}" ]
then
    MAKE=`which gmake`
fi

CC=`which gcc6`

# Configure

CC=`which gcc6` ./configure --prefix=$PREFIX \
  --without-python \
  --enable-shared \
  --disable-static \
  --with-zlib=${PREFIX} \
  --with-iconv=${PREFIX} \
  --without-lzma \
  CPPFLAGS="-I${PREFIX}/include" \
  CFLAGS="$CFLAGS -fPIC" \
  CXXFLAGS="$CFLAGS -fPIC" \
  LD_LIBRARY_PATH="${PREFIX}/lib" \
  LD_RUN_PATH="${PREFIX}/lib"

# Build

${MAKE} CC=gcc6 -s CFLAGS='${CFLAGS} -fPIC ' CXXFLAGS="$CFLAGS -fPIC"

# Install

${MAKE} CC=gcc6 install DESTDIR=${INSTALL_ROOT} \
      LDFLAGS="${LDFLAGS}" \
      LD_LIBRARY_PATH="${PREFIX}/lib" \
      LD_RUN_PATH="${PREFIX}/lib"


# Package

# rm -vf ${LXD}/bin/xmlcatalog
# rm -vf ${LXD}/bin/xmllint
# rm -vf ${LXD}/lib/libxml2.a
# rm -vf ${LXD}/lib/libxml2.la
# rm -vf ${LXD}/lib/xml2Conf.sh
# rm -rf ${LXD}/share

# mkdir -pv ${LX}/bin ${LX}/lib
# mv -vi ${LXD}${PREFIX}/lib/*.so* ${LX}/lib
