name: Build base images

on:
  schedule:
    - cron: "0 0 * * 0" # Every Sunday at midnight UTC
  workflow_dispatch: # Allows manual trigger

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    strategy:
      matrix:
        platform:
          - ubuntu-20
          - ubuntu-22
          - ubuntu-24
          - debian-11
          - debian-12
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Log in to ghcr.io
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        run: ./build-in-container.py --platform ${{ matrix.platform }} --push-image
