name: Lint with shellcheck

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt install shellcheck pipx && pipx install cfengine
      - name: Lint files with shellcheck and CFEngine CLI
        run: ./ci/lint.sh
