name: test stuff

on: push

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: test stuff
        run: |
          cat /etc/apt/sources.list
          for f in /etc/apt/sources.list.d; do
            echo $f
            cat $f
          done
