name: test multi-repo builds

on: [pull_request, push]

jobs:
  build:
    name: multi-repo build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: get other repo PRs from description
      id: get_prs
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        echo "pr_number=" $(gh pr view --json number -q .number || echo "")
        echo "GITHUB_CONTEXT is $GITHUB_CONTEXT"
        echo "body=${{github.event.pull_request.body}}"
    - name: do build
      run: |
        echo "body is ${{steps.get_prs.outputs.body}}"
        echo "pr_number is ${{steps.get_prs.outputs.pr_number}}"
