name: test multi-repo builds

on: [pull_request, push]

jobs:
  build:
    name: multi-repo build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v6
      id: get_issue_body
      with:
        script: |
          if (context.issue.body) {
            // Return issue body if present
            return context.issue.body;
          } else {
            // Otherwise return issue body from commit
            result =               await github.rest.repos.listPullRequestsAssociatedWithCommit({
                commit_sha: context.sha,
                owner: context.repo.owner,
                repo: context.repo.repo,
              });
            return result.data[0].body;
          }
        result-encoding: string
    - name: Issue number
      run: echo '${{steps.get_issue_body.outputs.result}}'
