name: test multi-repo builds

on: [pull_request, push]

jobs:
  build:
    name: multi-repo build
    runs-on: ubuntu-latest
    steps:
    - name: get other repo PRs from description
      id: get_prs
      run: |
        echo "body=${{github.event.pull_request.body}}"
    - name: do build
      run: |
        echo "${{steps.get_prs.outputs.body}}"
