name: test stuff

on: push

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: test stuff
        run: |
          sudo apt-get install -qy php7.4-cli
          which php
          php --version
          apt info php-cli
          #apt-cache search php
          sudo apt remove -y 'php8*'
          php --version
          du -hs /var/lib/docker
