name: test multi-repo builds

on: pull_request

jobs:
  build:
    name: multi-repo build
    steps:
    - name: get other repo PRs from description
      id: get_prs
      run: |
        echo "body=${{github.event.pull_request.body}}"
    - name: do build
      run: |
        echo "${{steps.get_prs.outputs.body}}"
