name: test multi-repo builds

on: [pull_request, push]

jobs:
  build:
    name: multi-repo build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v6
      id: get_issue_number
      with:
        script: |
          console.log(context)
          if (context.issue.number) {
            // Return issue number if present
            return context.issue.number;
          } else {
            // Otherwise return issue number from commit
result =               await github.rest.repos.listPullRequestsAssociatedWithCommit({
                commit_sha: context.sha,
                owner: context.repo.owner,
                repo: context.repo.repo,
              });
console.log(result);
          return "debugit!";
          }
        result-encoding: string
    - name: Issue number
      run: echo '${{steps.get_issue_number.outputs.result}}'
