name: test multi-repo builds

on: [pull_request, push]

jobs:
  build:
    name: multi-repo build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v6
      id: get_together_prs
      with:
        script: |
          const body = "";
          if (context.issue.body) {
            // Return issue body if present
            body = context.issue.body;
          } else {
            // Otherwise return issue body from commit
            result =               await github.rest.repos.listPullRequestsAssociatedWithCommit({
                commit_sha: context.sha,
                owner: context.repo.owner,
                repo: context.repo.repo,
              });
            body = result.data[0].body;
          }
          const regexp = /https:\/\/github.com\/cfengine\/([a-z]*)\/pull\/(\d*)/g;
          const matches = body.matchAll(regexp);
          const result = {};
          for (const match of matches) {
            result[match[1]] = match[2];
          }
          return result;
        result-encoding: json
    - name: Issue body
      run: echo '${{steps.get_together_prs.outputs.result}}'
