name: test multi-repo builds

on: [pull_request, push]

jobs:
  build:
    name: multi-repo build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v6
      id: get_together_prs
      with:
        script: |
          body = "";
          prs = {};
          if (context.issue.body) {
            // Return issue body if present
            body = context.issue.body;
          } else {
            // Otherwise return issue body from commit
            pull_requests = await github.rest.repos.listPullRequestsAssociatedWithCommit({
                commit_sha: context.sha,
                owner: context.repo.owner,
                repo: context.repo.repo,
              });
            body = pull_requests.data[0].body;
          }
          const regexp = /https:\/\/github.com\/cfengine\/([a-z]*)\/pull\/(\d*)/g;
          const matches = body.matchAll(regexp);
          for (const match of matches) {
            prs[match[1]] = match[2];
          }
          return prs;
        result-encoding: json
    - name: Build Together
      env:
        PRS: ${{steps.get_together_prs.outputs.result}}
      run: |
        echo "$PRS"
